#!/usr/bin/env python3
"""Capture the terrain primitives TerrainBuilder draws, for the landscape meshes.

The landscape meshes (tools/env/landscape/) must enclose the gameplay
terrain, which TerrainBuilder builds at server start from seeded
FillBall/FillBlock/FillCylinder calls. Roblox's `Random` can't be
reproduced offline, so this writes a Studio snippet that runs an exact copy
of TerrainBuilder's code against a recording stand-in for `Workspace.Terrain`
(same seed, same call order, so the same random draws) and returns every
shape call. Nothing in the place is written.

  python3 tools/env/landscape/capture.py compact [phase,phase...]
      -> tools/env/landscape/.capture_compact.luau (run with MCP execute_luau, Edit;
         keep each output under ~100k characters: capture in two groups)
  python3 tools/env/landscape/capture.py snippet [phase,phase...]   (standalone copy of the module)
  python3 tools/env/landscape/capture.py save <output.txt> [more.txt ...]
      -> assets/source/landscape/terrain_ops.txt (committed; the input of build.py)

Phases: floor washes road mesa cliffs buttes boulders.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
SRC = ROOT / "src" / "server" / "TerrainBuilder.luau"
SNIPPET = Path(__file__).resolve().parent / ".capture.luau"
OUT = ROOT / "assets" / "source" / "landscape" / "terrain_ops.txt"
PHASES = ["floor", "washes", "road", "mesa", "cliffs", "buttes", "boulders"]

PROXY = r'''
local __ops = {}
local __phase = "init"
local __want = { %s }
local function __n(v: number): string
	return string.format("%%.3f", v)
end
local function __rec(kind: string, parts: { string })
	if __want[__phase] then
		table.insert(__ops, __phase .. " " .. kind .. " " .. table.concat(parts, " "))
	end
end
local function __cf(cf: CFrame): { string }
	local _, _, _, r00, r01, r02, r10, r11, r12, r20, r21, r22 = cf:GetComponents()
	assert(math.abs(r00 - 1) < 1e-6 and math.abs(r11 - 1) < 1e-6 and math.abs(r22 - 1) < 1e-6
		and math.abs(r01) + math.abs(r02) + math.abs(r10) + math.abs(r12) + math.abs(r20) + math.abs(r21) < 1e-6, "rotated CFrame")
	return { __n(cf.X), __n(cf.Y), __n(cf.Z) }
end
local terrain: any = {
	FillBall = function(_, c: Vector3, r: number, m: Enum.Material)
		__rec("ball", { __n(c.X), __n(c.Y), __n(c.Z), __n(r), m.Name })
	end,
	FillBlock = function(_, cf: CFrame, s: Vector3, m: Enum.Material)
		local p = __cf(cf)
		__rec("block", { p[1], p[2], p[3], __n(s.X), __n(s.Y), __n(s.Z), m.Name })
	end,
	FillCylinder = function(_, cf: CFrame, h: number, r: number, m: Enum.Material)
		local p = __cf(cf)
		__rec("cyl", { p[1], p[2], p[3], __n(h), __n(r), m.Name })
	end,
	ReplaceMaterial = function(_, region: Region3, _res: number, from: Enum.Material, to: Enum.Material)
		local lo = region.CFrame.Position - region.Size / 2
		local hi = region.CFrame.Position + region.Size / 2
		-- material only (washes, road): not needed for the landscape shape
		local _ = { lo, hi, from, to }
	end,
	Clear = function() end,
	SetMaterialColor = function() end,
}
'''


def snippet(want):
    src = SRC.read_text()
    src = src.replace("--!strict\n", "")
    src, n = re.subn(r"^local terrain = Workspace\.Terrain\n", PROXY % ", ".join(f"{p} = true" for p in want), src, flags=re.M)
    assert n == 1, "terrain local not found"
    for p in PHASES:
        name = "build" + p.capitalize()
        src, n = re.subn(rf"^(local function {name}\(\)\n)", rf'\1\t__phase = "{p}"\n', src, flags=re.M)
        assert n == 1, name
    src, n = re.subn(r"local covered = applyMaterialVariants\(\)", "local covered = {}", src)
    assert n == 1
    tail = '\nTerrainBuilder.build()\nreturn #__ops .. "\\n" .. table.concat(__ops, "\\n")\n'
    src, n = re.subn(r"\nreturn TerrainBuilder\s*$", lambda _m: tail, src)
    assert n == 1
    SNIPPET.write_text(src)
    print(f"wrote {SNIPPET.relative_to(ROOT)} ({len(src)} chars) for phases {', '.join(want)}")


COMPACT = r'''-- Generated by tools/env/landscape/capture.py (compact): runs a patched copy
-- of the synced TerrainBuilder module against a recording terrain stand-in.
local function replace(s: string, a: string, b: string): string
	local i, j = string.find(s, a, 1, true)
	assert(i, "pattern not found: " .. a)
	return s:sub(1, i - 1) .. b .. s:sub((j :: number) + 1)
end
local src = game:GetService("ServerScriptService").Server.TerrainBuilder.Source
src = replace(src, "local terrain = Workspace.Terrain\n", [==[%s]==])
for _, p in { %s } do
	local name = "local function build" .. p:sub(1, 1):upper() .. p:sub(2) .. "()\n"
	src = replace(src, name, name .. "\t__phase = \"" .. p .. "\"\n")
end
src = replace(src, "local covered = applyMaterialVariants()", "local covered = {}")
local tail = "\nreturn TerrainBuilder"
local k = select(1, string.find(src, tail, #src - 40, true))
src = src:sub(1, (k :: number) - 1) .. "\nTerrainBuilder.build()\nreturn #__ops .. \"\\n\" .. table.concat(__ops, \"\\n\")\n"
local m = Instance.new("ModuleScript")
m.Name = "TerrainCapture"
m.Source = src
m.Parent = game:GetService("ServerStorage")
local ok, result = pcall(require, m)
m:Destroy()
assert(ok, result)
return result
'''


def compact_snippet(want):
    proxy = PROXY % ", ".join(f"{p} = true" for p in want)
    phases = ", ".join(f'"{p}"' for p in PHASES)
    code = COMPACT % (proxy, phases)
    path = SNIPPET.with_name(".capture_compact.luau")
    path.write_text(code)
    print(f"wrote {path.relative_to(ROOT)} ({len(code)} chars) for phases {', '.join(want)}")


# TerrainBuilder.build() call order (CSG order matters: later Air carves earlier solids).
BUILD_ORDER = ["floor", "cliffs", "buttes", "mesa", "boulders", "washes", "road"]


def save(files):
    """Merge one or more captures (each: count line + ops) into terrain_ops.txt,
    phases in TerrainBuilder's build order (a phase present in several
    captures is taken from the first)."""
    by_phase: dict = {}
    for f in files:
        text = Path(f).read_text().strip()
        if text.startswith('"') and text.endswith('"'):
            text = text[1:-1].encode().decode("unicode_escape")
        body = text.split("\n")
        count = int(body[0])
        ops = [ln for ln in body[1:] if ln.strip()]
        assert len(ops) == count, f"{f}: expected {count} ops, got {len(ops)}"
        mine: dict = {}
        for ln in ops:
            mine.setdefault(ln.split()[0], []).append(ln)
        for phase, phase_ops in mine.items():
            by_phase.setdefault(phase, phase_ops)
    lines = [ln for phase in BUILD_ORDER for ln in by_phase.get(phase, [])]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    header = [
        "# TerrainBuilder shape calls, captured in Studio by tools/env/landscape/capture.py",
        "# phase kind args...  (ball x y z r mat | block x y z sx sy sz mat | cyl x y z h r mat | paint lo hi from to)",
    ]
    OUT.write_text("\n".join(header + lines) + "\n")
    print(f"wrote {OUT.relative_to(ROOT)}: {len(lines)} ops")


if __name__ == "__main__":
    if len(sys.argv) >= 2 and sys.argv[1] == "compact":
        compact_snippet(sys.argv[2].split(",") if len(sys.argv) > 2 else PHASES)
    elif len(sys.argv) >= 2 and sys.argv[1] == "snippet":
        snippet(sys.argv[2].split(",") if len(sys.argv) > 2 else PHASES)
    elif len(sys.argv) >= 3 and sys.argv[1] == "save":
        save(sys.argv[2:])
    else:
        print(__doc__)
        sys.exit(2)
