#!/usr/bin/env python3
"""Probe rays: does the landscape mesh cover the real terrain from every camera?

Roblox voxelises TerrainBuilder's shapes on a 4-stud grid, so the rendered
terrain is not exactly the analytic shapes in terrain_ops.txt. This casts
the same rays against both: a Studio snippet raycasts the live terrain
(playtest, Server datamodel) from the game's cameras, and `check` intersects
those rays with the landscape meshes offline. A ray whose terrain hit comes
before its mesh hit shows terrain poking through the rock.

  python3 tools/env/landscape/probe.py snippet <camera>     # -> .probe_<camera>.luau
  python3 tools/env/landscape/probe.py save <camera> <file>  # Studio output -> assets/source/landscape/probes/
  Blender -b --factory-startup -P tools/env/landscape/probe.py -- check [Piece ...]   (BVH ray casts)
  Blender -b --factory-startup -P tools/env/landscape/probe.py -- los            (offline LOS vs the meshes)
  python3 tools/env/landscape/probe.py sweep            # -> .probe_sweep_*.luau (22 all-round viewpoints, Server)
  python3 tools/env/landscape/probe.py sweep <file>     # Studio output -> probes/sweep/*.txt
  Blender -b --factory-startup -P tools/env/landscape/probe.py -- sweep check
"""
from __future__ import annotations

import json
import math
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]
PROBES = ROOT / "assets" / "source" / "landscape" / "probes"
BUILD = ROOT / "assets" / "source" / "landscape" / "build"

# name: (position, look-at, grid columns, grid rows, horizontal half-angle, vertical half-angle) in degrees
CAMERAS = {
    "title": ((-62.0, 122.0, 122.0), (90.0, 0.0, -420.0), 72, 60, 33.0, 30.0),
    "turret": ((0.0, 80.0, 13.0), (0.0, 72.0, -87.0), 160, 36, 80.0, 18.0),
    "flank": ((430.0, 70.0, -700.0), (-20.0, 25.0, -190.0), 72, 60, 24.5, 22.5),
    "night": ((95.0, 30.0, -560.0), (-50.0, 70.0, -40.0), 72, 60, 24.5, 22.5),
    "defeat": ((60.0, 127.0, -140.0), (0.0, 30.0, 0.0), 64, 56, 33.0, 30.0),
}
LENGTH = 3000.0

SNIPPET = """-- Generated by tools/env/landscape/probe.py: terrain hit distance per ray.
local pos, look = Vector3.new({px}, {py}, {pz}), Vector3.new({lx}, {ly}, {lz})
local cf = CFrame.lookAt(pos, look)
local params = RaycastParams.new()
params.FilterType = Enum.RaycastFilterType.Include
params.FilterDescendantsInstances = {{ workspace.Terrain }}
local out = table.create({n})
for j = 0, {rows} - 1 do
	local v = math.tan(math.rad({vh})) * (1 - 2 * j / ({rows} - 1))
	for i = 0, {cols} - 1 do
		local u = math.tan(math.rad({hh})) * (2 * i / ({cols} - 1) - 1)
		local dir = (cf.LookVector + cf.RightVector * u + cf.UpVector * v).Unit
		local hit = workspace:Raycast(pos, dir * {length}, params)
		out[#out + 1] = if hit then string.format("%.2f", (hit.Position - pos).Magnitude) else "-1"
	end
end
return table.concat(out, ",")
"""


def rays(cam: str):
    import numpy as np

    pos, look, cols, rows, hh, vh = CAMERAS[cam]
    p = np.array(pos)
    f = np.array(look) - p
    f /= np.linalg.norm(f)
    r = np.cross(f, [0.0, 1.0, 0.0])
    r /= np.linalg.norm(r)
    up = np.cross(r, f)
    dirs = []
    for j in range(rows):
        v = math.tan(math.radians(vh)) * (1 - 2 * j / (rows - 1))
        for i in range(cols):
            u = math.tan(math.radians(hh)) * (2 * i / (cols - 1) - 1)
            d = f + r * u + up * v
            dirs.append(d / np.linalg.norm(d))
    return p, np.array(dirs)


def snippet(cam: str) -> None:
    pos, look, cols, rows, hh, vh = CAMERAS[cam]
    code = SNIPPET.format(px=pos[0], py=pos[1], pz=pos[2], lx=look[0], ly=look[1], lz=look[2], cols=cols, rows=rows,
                          hh=hh, vh=vh, n=cols * rows, length=LENGTH)
    path = HERE / f".probe_{cam}.luau"
    path.write_text(code)
    print(f"wrote {path.relative_to(ROOT)} ({cols * rows} rays)")


def save(cam: str, src: str) -> None:
    text = Path(src).read_text().strip().strip('"')
    vals = [float(x) for x in text.split(",")]
    _, _, cols, rows, _, _ = CAMERAS[cam]
    assert len(vals) == cols * rows, f"expected {cols * rows} values, got {len(vals)}"
    PROBES.mkdir(parents=True, exist_ok=True)
    (PROBES / f"{cam}.txt").write_text(",".join(f"{v:g}" for v in vals) + "\n")
    print(f"saved {len(vals)} terrain hits for {cam}")


def intersect(origin, dirs, v, f, far=LENGTH):
    """Nearest hit distance of each ray against triangles (v, f); inf if none.
    Uses Blender's BVH when run inside Blender, else brute force numpy."""
    import numpy as np

    try:
        from mathutils import Vector
        from mathutils.bvhtree import BVHTree
    except ImportError:
        return _intersect_numpy(origin, dirs, v, f, far)
    tree = BVHTree.FromPolygons([tuple(x) for x in v], [tuple(int(i) for i in t) for t in f], all_triangles=True)
    o = Vector(tuple(origin))
    out = np.full(len(dirs), np.inf)
    cos = np.ones(len(dirs))
    for i, d in enumerate(dirs):
        hit = tree.ray_cast(o, Vector(tuple(d)), far)
        if hit[0] is not None:
            out[i] = hit[3]
            cos[i] = abs(hit[1].dot(Vector(tuple(d))))
    intersect.cos = cos
    return out


def _intersect_numpy(origin, dirs, v, f, far=LENGTH):
    import numpy as np

    a, b, c = v[f[:, 0]], v[f[:, 1]], v[f[:, 2]]
    e1, e2 = b - a, c - a
    best = np.full(len(dirs), np.inf)
    # Cull triangles by angle from the origin: bin rays, test only nearby triangles.
    for start in range(0, len(dirs), 16):
        d = dirs[start:start + 16]
        pvec = np.cross(d[:, None, :], e2[None, :, :])
        det = np.einsum("tk,rtk->rt", e1, pvec)
        ok = np.abs(det) > 1e-9
        inv = np.where(ok, 1.0 / np.where(ok, det, 1.0), 0.0)
        tvec = origin - a
        uu = np.einsum("tk,rtk->rt", tvec, pvec) * inv
        qvec = np.cross(tvec, e1)
        vv = np.einsum("rk,tk->rt", d, qvec) * inv
        tt = np.einsum("tk,tk->t", e2, qvec)[None, :] * inv
        hit = ok & (uu >= 0) & (vv >= 0) & (uu + vv <= 1) & (tt > 0) & (tt < far)
        tt = np.where(hit, tt, np.inf)
        best[start:start + 16] = tt.min(axis=1)
    return best


def check(pieces: list[str]) -> int:
    import numpy as np

    sys.path.insert(0, str(HERE))
    from pieces import PIECES

    names = pieces or list(PIECES)
    meshes, terrains = [], []
    for n in names:
        p = BUILD / f"{n}.npz"
        if p.exists():
            d = np.load(p)
            meshes.append((n, d["low_v"].astype(np.float64), d["low_f"]))
            if "terrain_v" in d:
                terrains.append((n, d["terrain_v"].astype(np.float64), d["terrain_f"]))
    report = {}
    worst = 0.0
    for cam in CAMERAS:
        path = PROBES / f"{cam}.txt"
        if not path.exists():
            continue
        terrain = np.array([float(x) for x in path.read_text().strip().split(",")])
        origin, dirs = rays(cam)
        mesh = np.full(len(dirs), np.inf)
        owner = np.full(len(dirs), "", dtype=object)
        for n, v, f in meshes:
            # Only triangles in front of the camera and roughly inside its view.
            cen = v[f].mean(axis=1) - origin
            ok = (cen @ dirs.mean(axis=0)) > 0
            t = intersect(origin, dirs, v, f[ok])
            closer = t < mesh
            mesh = np.where(closer, t, mesh)
            owner = np.where(closer, n, owner)
        # Calibration: how far the live (voxel) terrain sits in front of the
        # analytic shapes, measured along the surface normal.
        ana = np.full(len(dirs), np.inf)
        ana_cos = np.ones(len(dirs))
        for n, v, f in terrains:
            t = intersect(origin, dirs, v, f)
            c = getattr(intersect, "cos", np.ones(len(dirs)))
            closer = t < ana
            ana = np.where(closer, t, ana)
            ana_cos = np.where(closer, c, ana_cos)
        has_t = terrain > 0
        # Rays where the landscape is what the camera sees: the mesh is hit
        # within 40 studs of the terrain hit (or the terrain is hit first).
        # Only rays whose live hit lies on the landscape's terrain (not a dune or boulder in front).
        relevant = has_t & np.isfinite(mesh) & np.isfinite(ana) & (np.abs(terrain - ana) * ana_cos < 4.0)
        gap = terrain - mesh  # > 0: the mesh is in front (good); < 0: terrain pokes out
        hitp = origin + dirs * np.where(has_t, terrain, 0.0)[:, None]
        in_pit = (np.hypot(hitp[:, 0], hitp[:, 2]) < 15.0) & (hitp[:, 1] > 57.0)  # under the emplacement
        relevant &= ~in_pit
        poke = relevant & (gap < -0.05)
        cal = has_t & np.isfinite(ana) & (np.abs(terrain - ana) < 30.0) & (ana_cos > 0.3)
        inflate = (ana - terrain) * ana_cos  # > 0: live terrain in front of the analytic surface
        by_kind = {}
        if cal.any():
            import ops as opsmod

            allops = [o for o in opsmod.load() if o.phase in ("cliffs", "buttes", "mesa")]
            pts = origin + dirs[cal] * ana[cal][:, None]
            best_d = np.full(len(pts), np.inf)
            kind = np.full(len(pts), "", dtype=object)
            for o in allops:
                if o.air:
                    continue
                d = np.abs(opsmod._shape(o, pts[:, 0], pts[:, 1], pts[:, 2], inflate=False))
                closer = d < best_d
                best_d = np.where(closer, d, best_d)
                kind = np.where(closer, o.kind, kind)
            infl = inflate[cal]
            for k in ("ball", "block", "cyl"):
                m = (kind == k) & (best_d < 1.0)
                if m.sum() > 5:
                    by_kind[k] = [int(m.sum())] + [round(float(np.percentile(infl[m], q)), 2) for q in (10, 50, 90)]
        report[cam] = {
            "inflation_by_kind_n_p10_p50_p90": by_kind,
            "calibration_rays": int(cal.sum()),
            "inflation_p50_p90_p99_max": [round(float(np.percentile(inflate[cal], q)), 2) for q in (50, 90, 99)] + [round(float(inflate[cal].max()), 2)] if cal.any() else None,
            "rays": int(len(dirs)), "on_landscape": int(relevant.sum()), "terrain_in_front": int(poke.sum()),
            "min_gap": round(float(gap[relevant].min()), 2) if relevant.any() else None,
            "median_gap": round(float(np.median(gap[relevant])), 2) if relevant.any() else None,
            "by_piece": {n: int((poke & (owner == n)).sum()) for n in names if (poke & (owner == n)).any()},
            "worst": [[round(float(c), 1) for c in (origin + dirs[i] * terrain[i])] + [round(float(gap[i]), 2), owner[i]]
                      for i in np.argsort(np.where(poke, gap, np.inf))[:6] if poke[i]],
        }
        if relevant.any():
            worst = min(worst, float(gap[relevant].min()))
    print(json.dumps(report, indent=1))
    return 1 if worst < -0.05 else 0


def lanes():
    """Config.Lanes parsed from src/shared/Config.luau: {name: [(x, z), ...]}."""
    import re

    text = (ROOT / "src" / "shared" / "Config.luau").read_text()
    block = text[text.index("Config.Lanes = {") + len("Config.Lanes = {"):]
    block = block[:block.index("\n}\n")]
    out = {}
    for name, body in re.findall(r"(\w+) = \{(.*?)\},", block, flags=re.S):
        out[name] = [(float(a), float(b)) for a, b in re.findall(r"Vector2\.new\((-?[\d.]+), (-?[\d.]+)\)", body)]
    return out


def los(pieces: list[str]) -> int:
    """Offline twin of RedMesaDebug losCheck against the landscape meshes only:
    muzzle (turret pivot + 6 along the sight line) to every lane end at
    feet/hip/head and along each lane every 20 studs at hip height. Live
    ground: floor y 2.0, wash ends -3.3 (P0 groundCheck)."""
    import numpy as np
    from mathutils import Vector
    from mathutils.bvhtree import BVHTree

    sys.path.insert(0, str(HERE))
    from pieces import PIECES

    verts, faces = [], []
    for n in pieces or list(PIECES):
        p = BUILD / f"{n}.npz"
        if p.exists():
            d = np.load(p)
            faces.append(d["low_f"] + sum(len(v) for v in verts))
            verts.append(d["low_v"].astype(np.float64))
    V, F = np.concatenate(verts), np.concatenate(faces)
    tree = BVHTree.FromPolygons([tuple(x) for x in V], [tuple(int(i) for i in t) for t in F], all_triangles=True)
    pivot = np.array([0.0, 72.0, 0.0])

    def ground(x, z):
        return -3.3 if abs(abs(x) - 90) < 1 and abs(z + 40) < 1 else 2.0

    def sight(target):
        d = target - pivot
        d /= np.linalg.norm(d)
        origin = pivot + d * 6.0
        delta = target - origin
        dist = np.linalg.norm(delta) - 0.25
        hit = tree.ray_cast(Vector(tuple(origin)), Vector(tuple(delta / np.linalg.norm(delta))), dist)
        return hit[0] is None, hit

    ok_all = True
    worst = []
    for name, pts in sorted(lanes().items()):
        ex, ez = pts[-1]
        g = ground(ex, ez)
        marks = []
        for label, h in (("feet", 0.5), ("hip", 3.0), ("head", 6.5)):
            vis, hit = sight(np.array([ex, g + h, ez]))
            marks.append(label + ("+" if vis else "-"))
            if label == "hip" and not vis:
                ok_all = False
                worst.append(f"{name} hip blocked at {tuple(round(c, 1) for c in hit[0])}")
        # along the lane, hip height, every 20 studs (floor ground)
        samples, hidden = 0, 0
        for i in range(len(pts) - 1):
            a, b = np.array(pts[i]), np.array(pts[i + 1])
            n = max(1, int(np.linalg.norm(b - a) // 20))
            for k in range(n):
                q = a + (b - a) * k / n
                samples += 1
                vis, _ = sight(np.array([q[0], 2.0 + 3.0, q[1]]))
                hidden += 0 if vis else 1
        print(f"{name:10s} end ({ex:.0f},{ez:.0f})  {' '.join(marks)}  along lane: {samples - hidden}/{samples} visible")
    # clearance: how far above each lane-end hip sight line the mesh comes
    print("LOS (meshes only):", "ALL PASS" if ok_all else "FAIL " + "; ".join(worst))
    return 0 if ok_all else 1


MESA_GRID = (-99.0, -99.0, 1.5, 133, 199)  # x0, z0, step, nx, nz

MESA_SNIPPET = """-- Generated by tools/env/landscape/probe.py mesa: live terrain top heights over the mesa.
local x0, z0, step, nx, nz = {x0}, {z0}, {step}, {nx}, {nz}
local params = RaycastParams.new()
params.FilterType = Enum.RaycastFilterType.Include
params.FilterDescendantsInstances = {{ workspace.Terrain }}
local DIG = "0123456789abcdefghijklmnopqrstuvwxyz"
local out = table.create(nx * nz)
for k = 0, nz - 1 do
	for i = 0, nx - 1 do
		local hit = workspace:Raycast(Vector3.new(x0 + i * step, 300, z0 + k * step), Vector3.new(0, -400, 0), params)
		local n = if hit then math.clamp(math.floor((hit.Position.Y + 10) * 10 + 0.5), 0, 46655) else 0
		out[#out + 1] = DIG:sub(n // 1296 + 1, n // 1296 + 1) .. DIG:sub((n // 36) % 36 + 1, (n // 36) % 36 + 1) .. DIG:sub(n % 36 + 1, n % 36 + 1)
	end
end
return table.concat(out)
"""


def mesa_snippet() -> None:
    x0, z0, step, nx, nz = MESA_GRID
    path = HERE / ".probe_mesa.luau"
    path.write_text(MESA_SNIPPET.format(x0=x0, z0=z0, step=step, nx=nx, nz=nz))
    print(f"wrote {path.relative_to(ROOT)} ({nx * nz} rays)")


def mesa_save(src: str) -> None:
    x0, z0, step, nx, nz = MESA_GRID
    data = Path(src).read_text().strip().strip('"')
    vals = [int(data[i:i + 3], 36) / 10.0 - 10.0 for i in range(0, len(data), 3)]
    assert len(vals) == nx * nz, len(vals)
    out = ROOT / "assets" / "source" / "landscape" / "mesa_heightfield.txt"
    out.write_text("# live terrain top heights over the mesa (probe.py mesa): x0 z0 step nx nz, then heights row by row (z-major)\n"
                   f"{x0} {z0} {step} {nx} {nz}\n" + ",".join(f"{v:.1f}" for v in vals) + "\n")
    print(f"wrote {out.relative_to(ROOT)}")


# Sweep viewpoints (ENV-2 fix): all-round ray rings from the basin, near the
# walls and buttes, the flanks and the turret, beyond the fixed cameras.
SWEEP = {
    "basin_c": (0.0, 8.0, -600.0), "basin_l": (-450.0, 8.0, -800.0), "basin_r": (450.0, 8.0, -800.0),
    "basin_far": (0.0, 8.0, -1150.0),  # inside Butte3's scree ring: its hits on Butte3 are skipped "basin_front": (0.0, 30.0, -250.0), "turret": (0.0, 80.0, 13.0),
    "flank_r": (430.0, 70.0, -700.0), "flank_l": (-430.0, 70.0, -700.0),
    "rear_r": (300.0, 20.0, 60.0), "rear_l": (-300.0, 20.0, 60.0),
    "butte1": (-380.0, 10.0, -980.0), "butte2": (260.0, 10.0, -980.0), "butte3": (-60.0, 10.0, -1060.0), "butte4": (620.0, 10.0, -930.0),
    "far_c": (0.0, 10.0, -1250.0), "far_l": (-600.0, 10.0, -1250.0), "far_r": (600.0, 10.0, -1250.0),
    "wall_r": (650.0, 10.0, -400.0), "wall_l": (-650.0, 10.0, -400.0), "wall_r2": (650.0, 10.0, 0.0), "wall_l2": (-650.0, 10.0, 0.0),
    "title": (-62.0, 122.0, 122.0),
}
SWEEP_AZ = 180  # every 2 degrees
SWEEP_EL = [-30.0 + 2.5 * i for i in range(27)]  # -30 .. +35 degrees


def sweep_dirs():
    import numpy as np

    out = []
    for el in SWEEP_EL:
        for i in range(SWEEP_AZ):
            az = math.radians(360.0 * i / SWEEP_AZ)
            e = math.radians(el)
            out.append((math.cos(e) * math.sin(az), math.sin(e), -math.cos(e) * math.cos(az)))
    return np.array(out)


SWEEP_SNIPPET = """-- Generated by tools/env/landscape/probe.py sweep: live terrain hits on all-round rings.
local views = {{ {views} }}
local params = RaycastParams.new()
params.FilterType = Enum.RaycastFilterType.Include
params.FilterDescendantsInstances = {{ workspace.Terrain }}
local DIG = "0123456789abcdefghijklmnopqrstuvwxyz"
local blocks = {{}}
for _, v in views do
	local name, pos = v[1], v[2]
	local out = {{}}
	for _, el in {{ {els} }} do
		local e = math.rad(el)
		for i = 0, {az} - 1 do
			local az = math.rad(360 * i / {az})
			local dir = Vector3.new(math.cos(e) * math.sin(az), math.sin(e), -math.cos(e) * math.cos(az))
			local hit = workspace:Raycast(pos, dir * 2600, params)
			if hit then
				local n = math.clamp(math.floor((hit.Position - pos).Magnitude * 10 + 0.5), 0, 46655)
				out[#out + 1] = DIG:sub(n // 1296 + 1, n // 1296 + 1) .. DIG:sub((n // 36) % 36 + 1, (n // 36) % 36 + 1) .. DIG:sub(n % 36 + 1, n % 36 + 1)
			else
				out[#out + 1] = "---"
			end
		end
	end
	table.insert(blocks, name .. ":" .. table.concat(out))
end
return table.concat(blocks, "\\n")
"""


def sweep_snippet(names) -> None:
    views = ", ".join(f'{{ "{n}", Vector3.new({SWEEP[n][0]}, {SWEEP[n][1]}, {SWEEP[n][2]}) }}' for n in names)
    code = SWEEP_SNIPPET.format(views=views, els=", ".join(f"{e:g}" for e in SWEEP_EL), az=SWEEP_AZ)
    path = HERE / f".probe_sweep_{names[0]}.luau"
    path.write_text(code)
    print(f"wrote {path.relative_to(ROOT)} ({len(names)} views, {len(names) * SWEEP_AZ * len(SWEEP_EL)} rays)")


def sweep_save(src: str) -> None:
    text = Path(src).read_text().strip().strip('"').replace("\\n", "\n")
    n_rays = SWEEP_AZ * len(SWEEP_EL)
    out_dir = PROBES / "sweep"
    out_dir.mkdir(parents=True, exist_ok=True)
    for line in text.split("\n"):
        if ":" not in line:
            continue
        name, data = line.split(":", 1)
        vals = [-1.0 if data[i:i + 3] == "---" else int(data[i:i + 3], 36) / 10.0 for i in range(0, len(data), 3)]
        assert len(vals) == n_rays, (name, len(vals))
        (out_dir / f"{name}.txt").write_text(",".join(f"{v:g}" for v in vals) + "\n")
        print(f"saved sweep {name}: {sum(v > 0 for v in vals)} hits")


def sweep_check(pieces: list[str]) -> int:
    """Rays where live terrain is hit in front of the landscape mesh."""
    import numpy as np

    sys.path.insert(0, str(HERE))
    from pieces import PIECES

    meshes, terrains = [], []
    for n in pieces or list(PIECES):
        d = np.load(BUILD / f"{n}.npz")
        meshes.append((n, d["low_v"].astype(np.float64), d["low_f"]))
        terrains.append((n, d["terrain_v"].astype(np.float64), d["terrain_f"]))
    dirs = sweep_dirs()
    worst_all = 0.0
    total_rel = total_poke = 0
    lines = []
    for name, pos in SWEEP.items():
        path = PROBES / "sweep" / f"{name}.txt"
        if not path.exists():
            continue
        terrain = np.array([float(x) for x in path.read_text().strip().split(",")])
        origin = np.array(pos)
        mesh = np.full(len(dirs), np.inf)
        owner = np.full(len(dirs), "", dtype=object)
        for n, v, f in meshes:
            t = intersect(origin, dirs, v, f)
            closer = t < mesh
            mesh, owner = np.where(closer, t, mesh), np.where(closer, n, owner)
        ana = np.full(len(dirs), np.inf)
        ana_cos = np.ones(len(dirs))
        for n, v, f in terrains:
            t = intersect(origin, dirs, v, f)
            c = getattr(intersect, "cos", np.ones(len(dirs)))
            closer = t < ana
            ana, ana_cos = np.where(closer, t, ana), np.where(closer, c, ana_cos)
        has_t = terrain > 0
        relevant = has_t & np.isfinite(mesh) & np.isfinite(ana) & (np.abs(terrain - ana) * ana_cos < 4.0)
        hitp = origin + dirs * np.where(has_t, terrain, 0.0)[:, None]
        relevant &= ~((np.hypot(hitp[:, 0], hitp[:, 2]) < 15.0) & (hitp[:, 1] > 57.0))  # under the emplacement
        # The basin floor itself (live y 2.0): the rock's talus toe dives under the sand there.
        relevant &= hitp[:, 1] > 2.8
        if name == "basin_far":
            relevant &= owner != "Butte3"
        gap = terrain - mesh
        poke = relevant & (gap < -0.05)
        total_rel += int(relevant.sum())
        total_poke += int(poke.sum())
        if relevant.any():
            worst_all = min(worst_all, float(gap[relevant].min()))
        worst = [f"({hitp[i][0]:.0f},{hitp[i][1]:.1f},{hitp[i][2]:.0f}) {gap[i]:.2f} {owner[i]}" for i in np.argsort(np.where(poke, gap, np.inf))[:4] if poke[i]]
        lines.append(f"{name:12s} rays on landscape {int(relevant.sum()):5d}  terrain in front {int(poke.sum()):4d}  " + "; ".join(worst))
    print("\n".join(lines))
    print(f"SWEEP: {total_rel} rays on the landscape, {total_poke} with live terrain in front of the mesh (worst {worst_all:.2f} studs)")
    return 0 if total_poke == 0 else 1


def _argv():
    return sys.argv[sys.argv.index("--") + 1:] if "--" in sys.argv else sys.argv[1:]


def main(argv):
    if len(argv) >= 2 and argv[0] == "snippet":
        for cam in argv[1:]:
            snippet(cam)
    elif len(argv) == 3 and argv[0] == "save":
        save(argv[1], argv[2])
    elif argv and argv[0] == "check":
        return check(argv[1:])
    elif argv and argv[0] == "sweep":
        if len(argv) > 1 and Path(argv[1]).exists():
            sweep_save(argv[1])
        elif len(argv) > 1 and argv[1] == "check":
            return sweep_check(argv[2:])
        else:
            names = list(SWEEP)
            for i in range(0, len(names), 6):
                sweep_snippet(names[i:i + 6])
    elif argv and argv[0] == "mesa":
        if len(argv) > 1:
            mesa_save(argv[1])
        else:
            mesa_snippet()
    elif argv and argv[0] == "los":
        return los(argv[1:])
    else:
        print(__doc__)
        return 2
    return 0


if __name__ == "__main__":
    code = main(_argv())
    if "bpy" not in sys.modules:
        sys.exit(code)
