#!/usr/bin/env python3
"""Upload a built asset to Roblox and generate its .rbxmx for Rojo.

Steps (see docs/ASSET_PIPELINE.md):
  1. python3 tools/assets/publish.py upload <Name>
       Uploads the GLB (Model) and PBR maps (Image) via Open Cloud when their
       hashes changed; ids cached in assets/exported/<Name>/roblox_ids.json.
       Writes tools/assets/.harvest/<Name>.luau, a Studio snippet that loads
       the uploaded model and returns its MeshIds as JSON.
  2. Run that snippet in Studio (Edit datamodel, e.g. MCP execute_luau) and
     save its output to a file, then
       python3 tools/assets/publish.py meshes <Name> <file-or-json>
     which validates mesh sizes and writes assets/roblox/<Name>.rbxmx.
  python3 tools/assets/publish.py harvest <Name...>   one Studio snippet for
       several assets; its output ({Name: meshes}) goes to
       python3 tools/assets/publish.py meshes <file-or-json>
  python3 tools/assets/publish.py rbxmx <Name>   regenerates the rbxmx only.

Requires ROBLOX_OPEN_CLOUD_KEY / ROBLOX_CREATOR_USER_ID in the environment
(`set -a; . ./.env.local; set +a`). The key is never printed.
"""
import hashlib
import json
import os
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
sys.path.insert(0, str(HERE))

import opencloud  # noqa: E402
import rbxmx  # noqa: E402

HARVEST = """-- Generated by tools/assets/publish.py: returns MeshIds of the uploaded model.
local model = game:GetService("InsertService"):LoadAsset({model_id})
local out = {{}}
for _, d in model:GetDescendants() do
	if d:IsA("MeshPart") then
		out[d.Name] = {{ id = d.MeshId, size = {{ d.Size.X, d.Size.Y, d.Size.Z }} }}
	end
end
model:Destroy()
return game:GetService("HttpService"):JSONEncode(out)
"""


def sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()[:16]


def paths(name: str):
    out = ROOT / "assets" / "exported" / name
    return out, out / "manifest.json", out / "roblox_ids.json"


def load(name: str):
    out, man_path, ids_path = paths(name)
    manifest = json.loads(man_path.read_text())
    ids = json.loads(ids_path.read_text()) if ids_path.exists() else {}
    return out, manifest, ids, ids_path


def save_ids(ids_path: Path, ids: dict) -> None:
    ids_path.write_text(json.dumps(ids, indent=1, sort_keys=True) + "\n")


def upload(name: str) -> None:
    out, manifest, ids, ids_path = load(name)
    hashes = ids.setdefault("hashes", {})
    glb = out / f"{name}.glb"
    h = sha(glb)
    if hashes.get("glb") != h or not ids.get("model"):
        res = opencloud.upload(str(glb), "Model", f"RMH_{name}")
        ids["model"] = res["assetId"]
        hashes["glb"] = h
        ids.pop("meshes", None)
        print(f"uploaded model {name}: {ids['model']}")
    else:
        print(f"model unchanged: {ids['model']}")
    tex = ids.setdefault("textures", {})
    # Forget maps of groups/channels the current build no longer has, so a
    # stale id (e.g. a dropped metalness map) never reaches the rbxmx.
    for group in list(tex):
        want = manifest["textures"].get(group, {})
        for ch in list(tex[group]):
            if ch not in want:
                del tex[group][ch]
                hashes.pop(f"{group}/{ch}", None)
        if not tex[group]:
            del tex[group]
    for group, files in manifest["textures"].items():
        for ch, fname in files.items():
            f = out / fname
            h = sha(f)
            key = f"{group}/{ch}"
            if hashes.get(key) == h and tex.get(group, {}).get(ch):
                continue
            res = opencloud.upload(str(f), "Image", f"RMH_{name}_{group}_{ch}")
            tex.setdefault(group, {})[ch] = f"rbxassetid://{res['assetId']}"
            hashes[key] = h
            print(f"uploaded {key}: {res['assetId']}")
    save_ids(ids_path, ids)
    hdir = HERE / ".harvest"
    hdir.mkdir(exist_ok=True)
    snippet = hdir / f"{name}.luau"
    snippet.write_text(HARVEST.format(model_id=ids["model"]))
    if ids.get("meshes"):
        print("meshes cached; run `publish.py rbxmx` if needed")
    else:
        print(f"next: run {snippet.relative_to(ROOT)} in Studio (Edit) and pass its JSON to `publish.py meshes {name}`")


def meshes(name: str, source: str) -> None:
    out, manifest, ids, ids_path = load(name)
    text = Path(source).read_text() if os.path.exists(source) else source
    data = {re.sub(r"\.\d{3}$", "", k): v for k, v in json.loads(text).items()}
    problems = []
    for p in manifest["parts"]:
        m = data.get(p["name"])
        if not m:
            problems.append(f"missing mesh for {p['name']}")
            continue
        got, want = m["size"], p["size"]
        if any(abs(g - w) > max(0.05, 0.02 * w) for g, w in zip(got, want)):
            problems.append(f"{p['name']}: imported size {got} != manifest {want}")
    if problems:
        print("WARNING:\n  " + "\n  ".join(problems))
    ids["meshes"] = {k: v["id"] for k, v in data.items()}
    save_ids(ids_path, ids)
    write_rbxmx(name)


HARVEST_MULTI = """-- Generated by tools/assets/publish.py harvest: MeshIds of uploaded models.
local result = {{}}
for name, id in {{ {entries} }} do
	local model = game:GetService("InsertService"):LoadAsset(id)
	local out = {{}}
	for _, d in model:GetDescendants() do
		if d:IsA("MeshPart") then
			out[d.Name] = {{ id = d.MeshId, size = {{ d.Size.X, d.Size.Y, d.Size.Z }} }}
		end
	end
	model:Destroy()
	result[name] = out
end
return game:GetService("HttpService"):JSONEncode(result)
"""


def harvest(names: list[str]) -> None:
    entries = []
    for n in names:
        _, _, ids, _ = load(n)
        entries.append(f"{n} = {ids['model']}")
    hdir = HERE / ".harvest"
    hdir.mkdir(exist_ok=True)
    path = hdir / "multi.luau"
    path.write_text(HARVEST_MULTI.format(entries=", ".join(entries)))
    print(path.read_text())


def meshes_multi(source: str) -> None:
    text = Path(source).read_text() if os.path.exists(source) else source
    for name, data in json.loads(text).items():
        print(f"== {name}")
        meshes(name, json.dumps(data))


def write_rbxmx(name: str) -> None:
    _, manifest, ids, _ = load(name)
    target = ROOT / "assets" / "roblox" / f"{name}.rbxmx"
    target.write_text(rbxmx.build(manifest, ids))
    print(f"wrote {target.relative_to(ROOT)}")


def main(argv):
    if len(argv) >= 2 and argv[0] == "upload":
        for n in argv[1:]:
            upload(n)
    elif len(argv) >= 2 and argv[0] == "harvest":
        harvest(argv[1:])
    elif len(argv) == 2 and argv[0] == "meshes":
        meshes_multi(argv[1])
    elif len(argv) == 3 and argv[0] == "meshes":
        meshes(argv[1], argv[2])
    elif len(argv) >= 2 and argv[0] == "rbxmx":
        for n in argv[1:]:
            write_rbxmx(n)
    else:
        print(__doc__)
        return 2
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main(sys.argv[1:]))
    except opencloud.OpenCloudError as e:
        print(f"error: {e}", file=sys.stderr)
        sys.exit(1)
