#!/usr/bin/env python3
"""Upload a built asset to Roblox and generate its .rbxmx for Rojo.

Steps (see docs/ASSET_PIPELINE.md):
  1. python3 tools/assets/publish.py upload <Name>
       Uploads the GLB (Model) and PBR maps (Image) via Open Cloud when their
       hashes changed; ids cached in assets/exported/<Name>/roblox_ids.json.
       Writes tools/assets/.harvest/<Name>.luau, a Studio snippet that loads
       the uploaded model and returns its MeshIds as JSON.
  2. Run that snippet in Studio (Edit datamodel, e.g. MCP execute_luau) and
     save its output to a file, then
       python3 tools/assets/publish.py meshes <Name> <file-or-json>
     which validates mesh sizes and writes assets/roblox/<Name>.rbxmx.
  python3 tools/assets/publish.py harvest <Name...>   one Studio snippet for
       several assets; its output ({Name: meshes}) goes to
       python3 tools/assets/publish.py meshes <file-or-json>
  python3 tools/assets/publish.py rbxmx <Name>   regenerates the rbxmx only.
Trim sheets (`manifest.kind == "trim"`, rmh/trim.py) upload their maps only;
assets with `shared_textures` point those groups at the sheet's image ids.

Requires ROBLOX_OPEN_CLOUD_KEY / ROBLOX_CREATOR_USER_ID in the environment
(`set -a; . ./.env.local; set +a`). The key is never printed.
"""
import hashlib
import json
import os
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
sys.path.insert(0, str(HERE))

import opencloud  # noqa: E402
import rbxmx  # noqa: E402

HARVEST = """-- Generated by tools/assets/publish.py: returns MeshIds of the uploaded model.
local model = game:GetService("InsertService"):LoadAsset({model_id})
local out = {{}}
for _, d in model:GetDescendants() do
	if d:IsA("MeshPart") then
		out[d.Name] = {{ id = d.MeshId, size = {{ d.Size.X, d.Size.Y, d.Size.Z }} }}
	end
end
model:Destroy()
return game:GetService("HttpService"):JSONEncode(out)
"""


def sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()[:16]


def paths(name: str):
    out = ROOT / "assets" / "exported" / name
    return out, out / "manifest.json", out / "roblox_ids.json"


def load(name: str):
    out, man_path, ids_path = paths(name)
    manifest = json.loads(man_path.read_text())
    ids = json.loads(ids_path.read_text()) if ids_path.exists() else {}
    return out, manifest, ids, ids_path


def save_ids(ids_path: Path, ids: dict) -> None:
    ids_path.write_text(json.dumps(ids, indent=1, sort_keys=True) + "\n")


def upload(name: str) -> None:
    out, manifest, ids, ids_path = load(name)
    hashes = ids.setdefault("hashes", {})
    trim_only = manifest.get("kind") == "trim"  # texture-only trim sheet (rmh/trim.py): no model
    for shared in manifest.get("shared_textures", {}).values():
        if not load(shared)[2].get("textures"):
            print(f"note: shared trim sheet {shared} has no uploaded maps yet; run `publish.py upload {shared}` first")
    glb = out / f"{name}.glb"
    h = sha(glb) if not trim_only else None
    if trim_only:
        pass
    elif hashes.get("glb") != h or not ids.get("model"):
        res = opencloud.upload(str(glb), "Model", f"RMH_{name}")
        ids["model"] = res["assetId"]
        hashes["glb"] = h
        ids.pop("meshes", None)
        print(f"uploaded model {name}: {ids['model']}")
    else:
        print(f"model unchanged: {ids['model']}")
    tex = ids.setdefault("textures", {})
    # Forget maps of groups/channels the current build no longer has, so a
    # stale id (e.g. a dropped metalness map) never reaches the rbxmx.
    for group in list(tex):
        want = manifest["textures"].get(group, {})
        for ch in list(tex[group]):
            if ch not in want:
                del tex[group][ch]
                hashes.pop(f"{group}/{ch}", None)
        if not tex[group]:
            del tex[group]
    for group, files in manifest["textures"].items():
        for ch, fname in files.items():
            f = out / fname
            h = sha(f)
            key = f"{group}/{ch}"
            if hashes.get(key) == h and tex.get(group, {}).get(ch):
                continue
            res = opencloud.upload(str(f), "Image", f"RMH_{name}_{group}_{ch}")
            tex.setdefault(group, {})[ch] = f"rbxassetid://{res['assetId']}"
            hashes[key] = h
            print(f"uploaded {key}: {res['assetId']}")
    upload_wreck(name, out, manifest, ids)
    save_ids(ids_path, ids)
    if trim_only:
        print(f"trim sheet {name}: maps uploaded; assets using it pick the ids up in `publish.py rbxmx`")
        return
    hdir = HERE / ".harvest"
    hdir.mkdir(exist_ok=True)
    snippet = hdir / f"{name}.luau"
    snippet.write_text(HARVEST.format(model_id=ids["model"]))
    if ids.get("meshes"):
        print("meshes cached; run `publish.py rbxmx` if needed")
    else:
        print(f"next: run {snippet.relative_to(ROOT)} in Studio (Edit) and pass its JSON to `publish.py meshes {name}`")


def upload_wreck(name: str, out: Path, manifest: dict, ids: dict) -> None:
    """Burnt-wreck colour maps (HS-5, `tools/assets/build.sh WreckMaps` ->
    `<Name>_<group>_wreck.png` + `wreck.json`). A map is uploaded (and
    later written into the rbxmx) only while the colour map it was derived
    from is still the group's current one; otherwise it is dropped with a
    warning, so a rebuilt asset never ships a wreck map for an old UV layout
    (Kit.char then falls back to tinting the live SurfaceAppearance)."""
    record_path = out / "wreck.json"
    record = json.loads(record_path.read_text()) if record_path.exists() else {}
    wreck = ids.setdefault("wreck", {})
    hashes = ids.setdefault("hashes", {})
    for group in list(wreck):
        if group not in record:
            del wreck[group]
            hashes.pop(f"wreck/{group}", None)
    for group, info in record.items():
        files = manifest.get("textures", {}).get(group, {})
        fresh = files.get("color") and sha(out / files["color"]) == info.get("source")
        if not fresh:
            print(f"WARNING {name}/{group}: wreck map is stale (colour map changed); "
                  "run `tools/assets/build.sh WreckMaps` - dropped for now")
            wreck.pop(group, None)
            hashes.pop(f"wreck/{group}", None)
            continue
        f = out / info["file"]
        h = sha(f)
        key = f"wreck/{group}"
        if hashes.get(key) == h and wreck.get(group):
            continue
        res = opencloud.upload(str(f), "Image", f"RMH_{name}_{group}_wreck")
        wreck[group] = f"rbxassetid://{res['assetId']}"
        hashes[key] = h
        print(f"uploaded {key}: {res['assetId']}")
    if not wreck:
        ids.pop("wreck", None)


def meshes(name: str, source: str) -> None:
    out, manifest, ids, ids_path = load(name)
    text = Path(source).read_text() if os.path.exists(source) else source
    data = {re.sub(r"\.\d{3}$", "", k): v for k, v in json.loads(text).items()}
    problems = []
    for p in manifest["parts"]:
        m = data.get(p["name"])
        if not m:
            problems.append(f"missing mesh for {p['name']}")
            continue
        got, want = m["size"], p["size"]
        if any(abs(g - w) > max(0.05, 0.02 * w) for g, w in zip(got, want)):
            problems.append(f"{p['name']}: imported size {got} != manifest {want}")
    if problems:
        print("WARNING:\n  " + "\n  ".join(problems))
    ids["meshes"] = {k: v["id"] for k, v in data.items()}
    save_ids(ids_path, ids)
    write_rbxmx(name)


HARVEST_MULTI = """-- Generated by tools/assets/publish.py harvest: MeshIds of uploaded models.
local result = {{}}
for name, id in {{ {entries} }} do
	local model = game:GetService("InsertService"):LoadAsset(id)
	local out = {{}}
	for _, d in model:GetDescendants() do
		if d:IsA("MeshPart") then
			out[d.Name] = {{ id = d.MeshId, size = {{ d.Size.X, d.Size.Y, d.Size.Z }} }}
		end
	end
	model:Destroy()
	result[name] = out
end
return game:GetService("HttpService"):JSONEncode(result)
"""


def harvest(names: list[str]) -> None:
    entries = []
    for n in names:
        _, _, ids, _ = load(n)
        entries.append(f"{n} = {ids['model']}")
    hdir = HERE / ".harvest"
    hdir.mkdir(exist_ok=True)
    path = hdir / "multi.luau"
    path.write_text(HARVEST_MULTI.format(entries=", ".join(entries)))
    print(path.read_text())


def meshes_multi(source: str) -> None:
    text = Path(source).read_text() if os.path.exists(source) else source
    for name, data in json.loads(text).items():
        print(f"== {name}")
        meshes(name, json.dumps(data))


def with_shared(manifest: dict, ids: dict) -> dict:
    """ids with the maps of shared texture groups (trim sheets, HS-3)
    resolved from the owning asset's roblox_ids.json."""
    shared = manifest.get("shared_textures", {})
    if not shared:
        return ids
    merged = dict(ids)
    merged["textures"] = dict(ids.get("textures", {}))
    for group, source in shared.items():
        src = load(source)[2].get("textures", {})
        maps = next(iter(src.values()), None) if len(src) == 1 else src.get("sheet")
        if not maps:
            raise SystemExit(f"{manifest['name']}: shared group {group} needs {source}'s maps: run `publish.py upload {source}`")
        merged["textures"][group] = maps
        src_wreck = load(source)[2].get("wreck", {})
        sheet_wreck = next(iter(src_wreck.values()), None) if len(src_wreck) == 1 else src_wreck.get("sheet")
        if sheet_wreck:
            merged["wreck"] = dict(merged.get("wreck", {}), **{group: sheet_wreck})
    return merged


def write_rbxmx(name: str) -> None:
    _, manifest, ids, _ = load(name)
    if manifest.get("kind") == "trim":
        print(f"{name} is a trim sheet (textures only): no rbxmx")
        return
    target = ROOT / "assets" / "roblox" / f"{name}.rbxmx"
    target.write_text(rbxmx.build(manifest, with_shared(manifest, ids)))
    print(f"wrote {target.relative_to(ROOT)}")


def main(argv):
    if len(argv) >= 2 and argv[0] == "upload":
        for n in argv[1:]:
            upload(n)
    elif len(argv) >= 2 and argv[0] == "harvest":
        harvest(argv[1:])
    elif len(argv) == 2 and argv[0] == "meshes":
        meshes_multi(argv[1])
    elif len(argv) == 3 and argv[0] == "meshes":
        meshes(argv[1], argv[2])
    elif len(argv) >= 2 and argv[0] == "rbxmx":
        for n in argv[1:]:
            write_rbxmx(n)
    else:
        print(__doc__)
        return 2
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main(sys.argv[1:]))
    except opencloud.OpenCloudError as e:
        print(f"error: {e}", file=sys.stderr)
        sys.exit(1)
