#!/usr/bin/env python3
"""Upload, harvest and write .rbxmx for SKINNED assets (rmh/skin.py).

    python3 tools/assets/skin_publish.py upload <Name>     # GLB + maps via Open Cloud (publish.upload)
    python3 tools/assets/skin_publish.py harvest <Name>    # prints a Studio snippet (run in Edit)
    python3 tools/assets/skin_publish.py meshes <Name> <json-file>
                                                          # checks sizes/bone positions, writes rbxmx
    python3 tools/assets/skin_publish.py rbxmx <Name>      # regenerate rbxmx from the cached harvest

What the Roblox importer makes of a skinned GLB (verified 2026-09-26):
a Model with one MeshPart per glTF mesh (named after the glTF *mesh*,
HasSkinnedMesh = true, plus a `<Mesh>Motor6D`), the Bone hierarchy (names
= Blender bone names) under a `RootPart` Part at the glTF origin when
there are several meshes, or under the MeshPart itself when there is one,
an AnimationController and an `InitialPoses` folder. Bones that no vertex
is weighted to are dropped. The whole asset is turned 180 degrees about
up, so the root bone carries that rotation.

The generated model per variant (`<prefix>_<Variant>`, see manifest meta
"rbxmx_prefix"):
    Model (PrimaryPart = Root)
      Root  Part, invisible, 2x2x1, at the asset pivot (hip centre), identity rotation
        <root bone> Bone ... (hierarchy as imported)
      Body  MeshPart (skinned) + SurfaceAppearance
      BodyLOD  MeshPart (skinned, Transparency 1) when the GLB has a LOD
Everything is turned back 180 degrees about up, so the model faces -Z and
every bone's rest rotation is identity in model space.
"""
import json
import os
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
sys.path.insert(0, str(HERE))

import rbxmx  # noqa: E402

HARVEST = """-- Generated by tools/assets/skin_publish.py: parts and bones of a skinned upload.
local model = game:GetService("InsertService"):LoadAsset({model_id})
local function r(v) return math.round(v * 1e5) / 1e5 end
local function cf(c) local t = {{ c:GetComponents() }} for i, v in t do t[i] = r(v) end return t end
local out = {{ parts = {{}}, bones = {{}} }}
for _, d in model:GetDescendants() do
	if d:IsA("MeshPart") then
		out.parts[d.Name] = {{ id = d.MeshId, size = {{ r(d.Size.X), r(d.Size.Y), r(d.Size.Z) }}, cf = cf(d.CFrame), skinned = d.HasSkinnedMesh }}
	elseif d:IsA("Bone") then
		local p = d.Parent
		table.insert(out.bones, {{ name = d.Name, parent = if p:IsA("Bone") then p.Name else "", host = p.Name, cf = cf(d.CFrame), world = cf(d.WorldCFrame) }})
	elseif d:IsA("BasePart") then
		out.root = {{ name = d.Name, cf = cf(d.CFrame) }}
	end
end
model:Destroy()
return game:GetService("HttpService"):JSONEncode(out)
"""


# --- tiny CFrame algebra (Roblox component order) ----------------------------

def cf(comp):
    x, y, z, *r = comp
    return ((x, y, z), (tuple(r[0:3]), tuple(r[3:6]), tuple(r[6:9])))


def cf_mul(a, b):
    (pa, Ra), (pb, Rb) = a, b
    R = tuple(tuple(sum(Ra[i][k] * Rb[k][j] for k in range(3)) for j in range(3)) for i in range(3))
    p = tuple(pa[i] + sum(Ra[i][k] * pb[k] for k in range(3)) for i in range(3))
    return (p, R)


def cf_inv(a):
    p, R = a
    Rt = tuple(tuple(R[j][i] for j in range(3)) for i in range(3))
    q = tuple(-sum(Rt[i][k] * p[k] for k in range(3)) for i in range(3))
    return (q, Rt)


TURN = ((0.0, 0.0, 0.0), ((-1.0, 0.0, 0.0), (0.0, 1.0, 0.0), (0.0, 0.0, -1.0)))  # 180 deg about Y


def clean(c, eps=1e-5):
    p, R = c
    p = tuple(0.0 if abs(v) < eps else round(v, 5) for v in p)
    R = tuple(tuple(0.0 if abs(v) < eps else round(v, 6) for v in row) for row in R)
    return (p, R)


# --- commands --------------------------------------------------------------------

def paths(name):
    out = ROOT / "assets" / "exported" / name
    return out, out / "manifest.json", out / "roblox_ids.json"


def load(name):
    out, man, ids = paths(name)
    return json.loads(man.read_text()), (json.loads(ids.read_text()) if ids.exists() else {}), ids


def upload(name):
    import publish

    publish.upload(name)
    manifest, ids, ids_path = load(name)
    if ids.get("skin", {}).get("model") != ids["model"] and "skin" in ids:
        ids.pop("skin")  # harvest belongs to an older upload
        ids_path.write_text(json.dumps(ids, indent=1, sort_keys=True) + "\n")
    print(f"model id {ids['model']}; next: skin_publish.py harvest {name}")


def harvest(name):
    _, ids, _ = load(name)
    hdir = HERE / ".harvest"
    hdir.mkdir(exist_ok=True)
    path = hdir / f"{name}_skin.luau"
    path.write_text(HARVEST.format(model_id=ids["model"]))
    print(path.read_text())


def meshes(name, source):
    manifest, ids, ids_path = load(name)
    text = Path(source).read_text() if os.path.exists(source) else source
    data = json.loads(text)
    # MeshPart names come from glTF *mesh* names, which may carry ".001".
    data["parts"] = {re.sub(r"\.\d{3}$", "", k): v for k, v in data["parts"].items()}
    problems = []
    for mname, m in manifest["meshes"].items():
        got = data["parts"].get(mname)
        if not got:
            problems.append(f"missing mesh {mname}")
            continue
        if not got.get("skinned"):
            problems.append(f"{mname}: HasSkinnedMesh is false")
        if any(abs(g - w) > max(0.05, 0.02 * w) for g, w in zip(got["size"], m["size"])):
            problems.append(f"{mname}: imported size {got['size']} != manifest {m['size']}")
    heads = {b["name"]: b["head"] for b in manifest["bones"]}
    for b in data["bones"]:
        world = cf_mul(TURN, cf(b["world"]))
        want = heads.get(b["name"])
        if want is None:
            problems.append(f"unexpected bone {b['name']}")
            continue
        if any(abs(world[0][i] - want[i]) > 0.01 for i in range(3)):
            problems.append(f"bone {b['name']}: turned world {world[0]} != manifest head {want}")
        if any(abs(world[1][i][j] - (1.0 if i == j else 0.0)) > 1e-3 for i in range(3) for j in range(3)):
            problems.append(f"bone {b['name']}: rest rotation not identity after the turn")
    missing = set(heads) - {b["name"] for b in data["bones"]}
    if missing:
        problems.append(f"bones missing after import: {sorted(missing)}")
    if problems:
        print("WARNING:\n  " + "\n  ".join(problems))
    else:
        print(f"harvest OK: {len(data['parts'])} meshes, {len(data['bones'])} bones, sizes and bone positions match")
    ids["skin"] = {"model": ids["model"], "parts": data["parts"], "bones": data["bones"], "root": data.get("root")}
    ids["meshes"] = {k: v["id"] for k, v in data["parts"].items()}
    ids_path.write_text(json.dumps(ids, indent=1, sort_keys=True) + "\n")
    write_rbxmx(name)


def build_variant(manifest, ids, variant, bones_under="Root"):
    ref = rbxmx.Ref()
    prefix = manifest.get("meta", {}).get("rbxmx_prefix", manifest["name"])
    model = rbxmx.Node("Model", f"{prefix}_{variant}", ref())
    skin = ids["skin"]
    pivot = tuple(manifest["pivot"])
    root_cf = (pivot, ((1.0, 0, 0), (0, 1.0, 0), (0, 0, 1.0)))

    root = rbxmx.Node("Part", "Root", ref())
    root.props += [
        rbxmx.vec3("size", (2, 2, 1)),
        rbxmx.cframe_xml("CoordinateFrame", "CFrame", root_cf[0], root_cf[1]),
        rbxmx.prop("bool", "Anchored", True),
        rbxmx.prop("bool", "CanCollide", False),
        rbxmx.prop("bool", "CanQuery", False),
        rbxmx.prop("bool", "CanTouch", False),
        rbxmx.prop("bool", "CastShadow", False),
        rbxmx.prop("float", "Transparency", 1),
        rbxmx.prop("token", "Material", rbxmx.MATERIALS["SmoothPlastic"]),
        rbxmx.color3((0.2, 0.2, 0.2)),
    ]
    model.children.append(root)
    model.props.append(f'<Ref name="PrimaryPart">{root.ref}</Ref>')

    tex = ids.get("textures", {}).get("main", {})
    part_nodes = {}
    for mname, m in manifest["meshes"].items():
        if m["variant"] != variant:
            continue
        got = skin["parts"][mname]
        world = clean(cf_mul(TURN, cf(got["cf"])))
        node = rbxmx.Node("MeshPart", "BodyLOD" if m["lod"] else "Body", ref())
        node.props += [
            rbxmx.prop("Content", "MeshId", got["id"]),
            rbxmx.vec3("InitialSize", got["size"]),
            rbxmx.vec3("size", got["size"]),
            rbxmx.cframe_xml("CoordinateFrame", "CFrame", world[0], world[1]),
            rbxmx.prop("bool", "Anchored", True),
            rbxmx.prop("bool", "CanCollide", False),
            rbxmx.prop("bool", "CanQuery", False),
            rbxmx.prop("bool", "CanTouch", False),
            rbxmx.prop("bool", "CastShadow", not m["lod"]),
            rbxmx.prop("token", "CollisionFidelity", rbxmx.FIDELITY["Box"]),
            rbxmx.prop("float", "Transparency", 1 if m["lod"] else 0),
            rbxmx.prop("token", "Material", rbxmx.MATERIALS["Fabric"]),
            rbxmx.color3((1, 1, 1)),
        ]
        if tex:
            sa = rbxmx.Node("SurfaceAppearance", "SurfaceAppearance", ref())
            for key, prop_name in (("color", "ColorMap"), ("normal", "NormalMap"), ("rough", "RoughnessMap"), ("metal", "MetalnessMap")):
                if tex.get(key):
                    sa.props.append(rbxmx.prop("Content", prop_name, tex[key]))
            node.children.append(sa)
        model.children.append(node)
        part_nodes["BodyLOD" if m["lod"] else "Body"] = (node, world)

    host_node, host_cf = (root, root_cf) if bones_under == "Root" else part_nodes[bones_under]
    bone_nodes = {}
    for b in skin["bones"]:
        node = rbxmx.Node("Bone", b["name"], ref())
        if b["parent"]:
            rel = clean(cf(b["cf"]))
            bone_nodes[b["parent"]].children.append(node)
        else:
            # Root bones: the importer hangs them on RootPart (several meshes)
            # or on the MeshPart itself (one mesh); use the world CFrame.
            world = cf_mul(TURN, cf(b["world"]))
            rel = clean(cf_mul(cf_inv(host_cf), world))
            host_node.children.append(node)
        node.props.append(rbxmx.cframe_xml("CoordinateFrame", "CFrame", rel[0], rel[1]))
        bone_nodes[b["name"]] = node
    model.props.append(rbxmx.cframe_xml("OptionalCoordinateFrame", "WorldPivotData", root_cf[0], root_cf[1]))
    body = model.xml()
    return f'<roblox xmlns:xmime="http://www.w3.org/2005/05/xmlmime" version="4">\n{body}\n</roblox>\n'


def write_rbxmx(name):
    manifest, ids, _ = load(name)
    if ids.get("skin", {}).get("model") != ids.get("model"):
        raise SystemExit(f"{name}: no harvest for model {ids.get('model')}; run `skin_publish.py harvest {name}` in Studio first")
    prefix = manifest.get("meta", {}).get("rbxmx_prefix", manifest["name"])
    for v in manifest["variants"]:
        target = ROOT / "assets" / "roblox" / f"{prefix}_{v}.rbxmx"
        target.write_text(build_variant(manifest, ids, v))
        print(f"wrote {target.relative_to(ROOT)}")


def main(argv):
    if len(argv) == 2 and argv[0] == "upload":
        upload(argv[1])
    elif len(argv) == 2 and argv[0] == "harvest":
        harvest(argv[1])
    elif len(argv) == 3 and argv[0] == "meshes":
        meshes(argv[1], argv[2])
    elif len(argv) == 2 and argv[0] == "rbxmx":
        write_rbxmx(argv[1])
    else:
        print(__doc__)
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
