#!/usr/bin/env python3
"""Captures the live battlefield for the Blender title key art (LOOK-4).

The key art is rebuilt in Blender from the real game assets. What Roblox
builds at server start (the voxel terrain surface and its paint, and where
the ground dressing, boulders, road/wash strips and landscape meshes were
placed) only exists in a running game, so a Studio snippet records it:

  - the terrain top surface on a 4-stud grid over the whole basin
    (raycast against Terrain only): height and material per sample;
  - every visible BasePart in Workspace: full name, class, MeshId, CFrame,
    Size, Material, Color, Transparency.

The snippet talks HTTP to a local sink (Studio allows localhost; the
snippet turns HttpService.HttpEnabled on for its own call):

  python3 tools/ui/keyart_capture.py sink <out_dir> &     # port 34998
  python3 tools/ui/keyart_capture.py snippet              # -> tools/ui/.keyart_capture.luau
  (run it with execute_luau in the Server datamodel ~40 s after Play)
  tools/ui/py.sh tools/ui/keyart_capture.py save <out_dir>   (numpy)
      -> assets/ui/art/src/keyart_terrain.npz (heights, materials, grid)
         assets/ui/art/src/keyart_parts.json
         assets/ui/art/art.json "capture_rev" (HEAD: the commit whose asset
         ids the capture matches; take it on a clean, committed asset state)

Heights: y = code / YQ - Y0 (0.08-stud steps, -40..287).
"""
from __future__ import annotations

import http.server
import json
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
HERE = Path(__file__).resolve().parent
DEST = ROOT / "assets" / "ui" / "art" / "src"
PORT = 34998
B64 = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"
MATERIALS = ["Sand", "Mud", "Ground", "Salt", "Rock", "Sandstone", "Limestone", "Slate", "Grass", "Concrete"]
Y0, YQ = 40.0, 12.5
STEP = 4
X0, X1 = -1000, 1000
Z0, Z1 = -1520, 160
ROWS_PER_POST = 40

RUNNER = """-- Generated by tools/ui/keyart_capture.py (LOOK-4 key art capture).
local Http = game:GetService("HttpService")
Http.HttpEnabled = true
local B = "{b64}"
local MATS = {{ {mats} }}
local function enc(v)
	v = math.clamp(math.floor(v + 0.5), 0, 4095)
	local hi, lo = v // 64, v % 64
	return string.sub(B, hi + 1, hi + 1) .. string.sub(B, lo + 1, lo + 1)
end
local tp = RaycastParams.new()
tp.FilterType = Enum.RaycastFilterType.Include
tp.FilterDescendantsInstances = {{ workspace.Terrain }}
local rows, batch, posted = {{}}, 0, 0
local function flush()
	if #rows == 0 then return end
	Http:PostAsync("http://localhost:{port}/terrain_" .. batch .. ".txt", table.concat(rows, ";"), Enum.HttpContentType.TextPlain)
	batch += 1
	posted += #rows
	table.clear(rows)
end
for z = {z0}, {z1}, {step} do
	local parts = {{}}
	for x = {x0}, {x1}, {step} do
		local hit = workspace:Raycast(Vector3.new(x, 400, z), Vector3.new(0, -460, 0), tp)
		parts[#parts + 1] = if hit then enc((hit.Position.Y + {y0}) * {yq}) .. (MATS[hit.Material.Name] or "z") else "~~z"
	end
	rows[#rows + 1] = table.concat(parts)
	if #rows >= {per_post} then flush() end
end
flush()
-- Every visible part.
local list = {{}}
local chunk = 0
local function flushParts()
	if #list == 0 then return end
	Http:PostAsync("http://localhost:{port}/parts_" .. chunk .. ".json", Http:JSONEncode(list), Enum.HttpContentType.ApplicationJson)
	chunk += 1
	table.clear(list)
end
local count = 0
for _, d in workspace:GetDescendants() do
	if d:IsA("BasePart") and d ~= workspace.Terrain and d.Transparency < 0.99 and not d:IsDescendantOf(workspace.CurrentCamera) then
		local model = d:FindFirstAncestorOfClass("Model")
		if not (model and game.Players:GetPlayerFromCharacter(model)) then
			local c = table.pack(d.CFrame:GetComponents())
			local sa = d:FindFirstChildOfClass("SurfaceAppearance")
			list[#list + 1] = {{
				n = d:GetFullName(),
				c = d.ClassName,
				m = if d:IsA("MeshPart") then d.MeshId else "",
				t = if d:IsA("MeshPart") then d.TextureID else "",
				sa = if sa then sa.ColorMap else "",
				cf = {{ c[1], c[2], c[3], c[4], c[5], c[6], c[7], c[8], c[9], c[10], c[11], c[12] }},
				s = {{ d.Size.X, d.Size.Y, d.Size.Z }},
				mat = d.Material.Name,
				col = {{ d.Color.R, d.Color.G, d.Color.B }},
				tr = d.Transparency,
			}}
			count += 1
			if #list >= 700 then flushParts() end
		end
	end
end
flushParts()
return string.format("terrain rows %d in %d posts; parts %d in %d posts", posted, batch, count, chunk)
"""


def sink(out_dir: str) -> None:
    os.makedirs(out_dir, exist_ok=True)

    class Handler(http.server.BaseHTTPRequestHandler):
        def do_POST(self):  # noqa: N802
            n = int(self.headers.get("Content-Length", 0))
            body = self.rfile.read(n)
            name = os.path.basename(self.path.strip("/")) or "post"
            with open(os.path.join(out_dir, name), "wb") as f:
                f.write(body)
            self.send_response(200)
            self.end_headers()
            self.wfile.write(b"ok %d" % len(body))

        def log_message(self, *args):
            pass

    http.server.HTTPServer(("127.0.0.1", PORT), Handler).serve_forever()


def snippet() -> None:
    mats = ", ".join(f'{m} = "{B64[i]}"' for i, m in enumerate(MATERIALS))
    code = RUNNER.format(b64=B64, mats=mats, port=PORT, x0=X0, x1=X1, z0=Z0, z1=Z1, step=STEP, y0=Y0, yq=YQ, per_post=ROWS_PER_POST)
    path = HERE / ".keyart_capture.luau"
    path.write_text(code)
    print(f"wrote {path.relative_to(ROOT)} ({len(code)} chars)")


def save(out_dir: str) -> None:
    import numpy as np  # only the save step needs it (tools/ui/py.sh)

    src = Path(out_dir)
    files = sorted(src.glob("terrain_*.txt"), key=lambda p: int(p.stem.split("_")[1]))
    rows = []
    for f in files:
        rows += f.read_text().split(";")
    xs = np.arange(X0, X1 + 1, STEP)
    zs = np.arange(Z0, Z1 + 1, STEP)
    if len(rows) != len(zs):
        raise SystemExit(f"expected {len(zs)} rows, got {len(rows)}")
    lut = {c: i for i, c in enumerate(B64)}
    height = np.full((len(zs), len(xs)), np.nan, dtype=np.float32)
    mat = np.full((len(zs), len(xs)), -1, dtype=np.int8)
    for r, row in enumerate(rows):
        if len(row) != 3 * len(xs):
            raise SystemExit(f"row {r}: {len(row)} chars, expected {3 * len(xs)}")
        for i in range(len(xs)):
            a, b, m = row[3 * i], row[3 * i + 1], row[3 * i + 2]
            if a == "~":
                continue
            height[r, i] = (lut[a] * 64 + lut[b]) / YQ - Y0
            mat[r, i] = lut.get(m, -1) if m != "z" else -1
    DEST.mkdir(parents=True, exist_ok=True)
    np.savez_compressed(DEST / "keyart_terrain.npz", height=height, mat=mat, xs=xs, zs=zs, materials=np.array(MATERIALS))
    parts = []
    for f in sorted(src.glob("parts_*.json"), key=lambda p: int(p.stem.split("_")[1])):
        parts += json.loads(f.read_text())
    (DEST / "keyart_parts.json").write_text(json.dumps(parts, separators=(",", ":")) + "\n")
    # The mesh ids in the capture belong to this commit's assets; the key art
    # render resolves them against it (keyart_scene.capture_rev).
    import subprocess

    rev = subprocess.run(["git", "-C", str(ROOT), "rev-parse", "--short", "HEAD"], capture_output=True, text=True, check=True).stdout.strip()
    meta_path = ROOT / "assets" / "ui" / "art" / "art.json"
    meta = json.loads(meta_path.read_text()) if meta_path.exists() else {}
    meta["capture_rev"] = rev
    meta_path.write_text(json.dumps(meta, indent=1, sort_keys=True) + "\n")
    counts = {m: int((mat == i).sum()) for i, m in enumerate(MATERIALS)}
    print(f"terrain {height.shape}, missing {int(np.isnan(height).sum())}, y {np.nanmin(height):.1f}..{np.nanmax(height):.1f}; {counts}")
    print(f"parts {len(parts)}")


def main(argv: list[str]) -> int:
    if not argv:
        print(__doc__)
        return 2
    if argv[0] == "sink":
        sink(argv[1])
    elif argv[0] == "snippet":
        snippet()
    elif argv[0] == "save":
        save(argv[1])
    else:
        print(__doc__)
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
