#!/usr/bin/env python3
"""Uploads the Look textures and writes the client id module.

    set -a; . ./.env.local; set +a            # Open Cloud credentials (never printed)
    python3 tools/ui/publish_look.py upload    # assets/ui/look/*.png -> private Image assets
    python3 tools/ui/publish_look.py luau      # src/client/PostFxAssets.luau

Uploads go through tools/assets/opencloud.py as private `Image` assets. Ids
are cached per file hash in assets/ui/look/roblox_ids.json, so unchanged
files are skipped.
"""
from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
LOOK = ROOT / "assets" / "ui" / "look"
IDS = LOOK / "roblox_ids.json"
LUAU = ROOT / "src" / "client" / "PostFxAssets.luau"


def sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()[:16]


def load_ids() -> dict:
    return json.loads(IDS.read_text()) if IDS.exists() else {"hashes": {}, "ids": {}}


def save_ids(ids: dict) -> None:
    IDS.write_text(json.dumps(ids, indent=1, sort_keys=True) + "\n")


def upload(names: list[str]) -> None:
    sys.path.insert(0, str(ROOT / "tools" / "assets"))
    import opencloud  # noqa: E402  (needs the Open Cloud env vars)

    ids = load_ids()
    files = [LOOK / f"{n}.png" for n in names] if names else sorted(LOOK.glob("*.png"))
    for f in files:
        key = f.stem
        h = sha(f)
        if ids["hashes"].get(key) == h and ids["ids"].get(key):
            print(f"unchanged {key}")
            continue
        res = opencloud.upload(str(f), "Image", f"RMH_Look_{key}", "Red Mesa Holdout lighting/post texture")
        ids["ids"][key] = f"rbxassetid://{res['assetId']}"
        ids["hashes"][key] = h
        save_ids(ids)
        print(f"uploaded {key}: {res['assetId']}")
    save_ids(ids)


def write_luau() -> None:
    ids = load_ids()["ids"]
    lines = [
        "--!strict\n",
        "-- GENERATED by tools/ui/publish_look.py luau — do not edit by hand.\n",
        "-- Image ids for the Look workstream's lighting/post textures\n",
        "-- (assets/ui/look/*.png, made by tools/ui/look_textures.py).\n\n",
        "return {\n",
    ]
    for key in sorted(ids):
        lines.append(f'\t{key} = "{ids[key]}",\n')
    lines.append("}\n")
    LUAU.write_text("".join(lines))
    print("wrote", LUAU.relative_to(ROOT))


def main(argv: list[str]) -> int:
    if argv and argv[0] == "upload":
        upload(argv[1:])
        return 0
    if argv and argv[0] == "luau":
        write_luau()
        return 0
    print(__doc__)
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
