#!/usr/bin/env python3
"""Uploads the Look textures and writes the client id modules.

    set -a; . ./.env.local; set +a                 # Open Cloud credentials (never printed)
    python3 tools/ui/publish_look.py upload         # assets/ui/look/*.png -> private Image assets
    python3 tools/ui/publish_look.py luau           # src/client/PostFxAssets.luau
    python3 tools/ui/publish_look.py upload --set kit   # assets/ui/kit/*.png (LOOK-2 HUD kit)
    python3 tools/ui/publish_look.py luau --set kit     # src/client/UiKitAssets.luau (ids + atlas rects)
    python3 tools/ui/publish_look.py upload --set motion  # assets/ui/motion/*.png (LOOK-3 tread strips)
    python3 tools/ui/publish_look.py luau --set motion    # src/client/EnemyMotionAssets.luau
    python3 tools/ui/publish_look.py upload --set art   # assets/ui/art/*.png (LOOK-4 icons, key art, logo)
    python3 tools/ui/publish_look.py luau --set art     # src/client/UiKitArtAssets.luau (ids + icon cells)

Uploads go through tools/assets/opencloud.py as private `Image` assets. Ids
are cached per file hash in assets/ui/<set>/roblox_ids.json, so unchanged
files are skipped.
"""
from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SETS = {
    # set: (texture dir, generated module, asset name prefix, description)
    "look": (ROOT / "assets" / "ui" / "look", ROOT / "src" / "client" / "PostFxAssets.luau",
             "RMH_Look_", "Red Mesa Holdout lighting/post texture"),
    "kit": (ROOT / "assets" / "ui" / "kit", ROOT / "src" / "client" / "UiKitAssets.luau",
            "RMH_UiKit_", "Red Mesa Holdout HUD kit texture"),
    "motion": (ROOT / "assets" / "ui" / "motion", ROOT / "src" / "client" / "EnemyMotionAssets.luau",
               "RMH_Motion_", "Red Mesa Holdout enemy motion texture"),
    "art": (ROOT / "assets" / "ui" / "art", ROOT / "src" / "client" / "UiKitArtAssets.luau",
            "RMH_UiArt_", "Red Mesa Holdout UI art"),
}


def sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()[:16]


def ids_path(folder: Path) -> Path:
    return folder / "roblox_ids.json"


def load_ids(folder: Path) -> dict:
    p = ids_path(folder)
    return json.loads(p.read_text()) if p.exists() else {"hashes": {}, "ids": {}}


def save_ids(folder: Path, ids: dict) -> None:
    ids_path(folder).write_text(json.dumps(ids, indent=1, sort_keys=True) + "\n")


def upload(set_name: str, names: list[str]) -> None:
    sys.path.insert(0, str(ROOT / "tools" / "assets"))
    import opencloud  # noqa: E402  (needs the Open Cloud env vars)

    folder, _, prefix, description = SETS[set_name]
    ids = load_ids(folder)
    files = [folder / f"{n}.png" for n in names] if names else sorted(folder.glob("*.png"))
    for f in files:
        key = f.stem
        h = sha(f)
        if ids["hashes"].get(key) == h and ids["ids"].get(key):
            print(f"unchanged {key}")
            continue
        res = opencloud.upload(str(f), "Image", f"{prefix}{key}", description)
        ids["ids"][key] = f"rbxassetid://{res['assetId']}"
        ids["hashes"][key] = h
        save_ids(folder, ids)
        print(f"uploaded {key}: {res['assetId']}")
    save_ids(folder, ids)


def write_look_luau() -> None:
    folder, luau, _, _ = SETS["look"]
    ids = load_ids(folder)["ids"]
    lines = [
        "--!strict\n",
        "-- GENERATED by tools/ui/publish_look.py luau — do not edit by hand.\n",
        "-- Image ids for the Look workstream's lighting/post textures\n",
        "-- (assets/ui/look/*.png, made by tools/ui/look_textures.py).\n\n",
        "return {\n",
    ]
    for key in sorted(ids):
        lines.append(f'\t{key} = "{ids[key]}",\n')
    lines.append("}\n")
    luau.write_text("".join(lines))
    print("wrote", luau.relative_to(ROOT))


def write_motion_luau() -> None:
    folder, luau, _, _ = SETS["motion"]
    ids = load_ids(folder)["ids"]
    lines = [
        "--!strict\n",
        "-- GENERATED by tools/ui/publish_look.py luau --set motion — do not edit by hand.\n",
        "-- Image ids for the Look workstream's motion textures\n",
        "-- (assets/ui/motion/*.png, made by tools/ui/motion_textures.py).\n\n",
        "return {\n",
    ]
    for key in sorted(ids):
        lines.append(f'\t{key} = "{ids[key]}",\n')
    lines.append("} :: { [string]: string }\n")
    luau.write_text("".join(lines))
    print("wrote", luau.relative_to(ROOT))


def write_kit_luau() -> None:
    folder, luau, _, _ = SETS["kit"]
    ids = load_ids(folder)["ids"]
    atlas = json.loads((folder / "atlas.json").read_text())
    missing = [k for k in ("kit_atlas", "kit_grain", "kit_hazard", "kit_strip") if k not in ids]
    if missing:
        raise SystemExit(f"not uploaded yet: {', '.join(missing)}")
    lines = [
        "--!strict\n",
        "-- GENERATED by tools/ui/publish_look.py luau --set kit — do not edit by hand.\n",
        "-- HUD kit textures (assets/ui/kit/*.png, made by tools/ui/ui_kit_textures.py):\n",
        "-- one atlas (cells: pixel offset/size, 9-slice centre in cell pixels) and\n",
        "-- three tiles.\n\n",
        "return {\n",
        f'\tatlas = "{ids["kit_atlas"]}",\n',
        f'\tgrain = "{ids["kit_grain"]}",\n',
        f'\thazard = "{ids["kit_hazard"]}",\n',
        f'\tstrip = "{ids["kit_strip"]}",\n',
        "\tcells = {\n",
    ]
    for name in sorted(atlas["cells"]):
        c = atlas["cells"][name]
        (x, y), (w, h) = c["offset"], c["size"]
        entry = f"offset = Vector2.new({x}, {y}), size = Vector2.new({w}, {h})"
        if "slice" in c:
            l, t, r, b = c["slice"]
            entry += f", slice = Rect.new({l}, {t}, {r}, {b})"
        lines.append(f"\t\t{name} = {{ {entry} }},\n")
    lines += ["\t},\n", "}\n"]
    luau.write_text("".join(lines))
    print("wrote", luau.relative_to(ROOT))


def png_size(path: Path) -> tuple[int, int]:
    """Width and height from a PNG's IHDR chunk."""
    head = path.read_bytes()[16:24]
    return int.from_bytes(head[:4], "big"), int.from_bytes(head[4:], "big")


def write_art_luau() -> None:
    """UiKitArtAssets.luau: the weapon icon atlas (+ cells), the title logo and,
    once rendered and uploaded, the title key art. A missing key art writes
    `keyart = nil` (the title keeps its live camera)."""
    folder, luau, _, _ = SETS["art"]
    ids = load_ids(folder)["ids"]
    meta = json.loads((folder / "art.json").read_text())
    missing = [k for k in ("weapon_icons", "title_logo") if k not in ids]
    if missing:
        raise SystemExit(f"not uploaded yet: {', '.join(missing)}")
    logo_w, logo_h = png_size(folder / "title_logo.png")
    lines = [
        "--!strict\n",
        "-- GENERATED by tools/ui/publish_look.py luau --set art — do not edit by hand.\n",
        "-- LOOK-4 UI art (assets/ui/art/*.png): weapon icons rendered from the\n",
        "-- emplacement's weapons (tools/ui/weapon_icons.py; atlas cells in pixels),\n",
        "-- the title key art rendered in Blender from the game's assets\n",
        "-- (tools/ui/keyart_scene.py; stored anamorphic: `keyartAspect` is the display\n",
        "-- width/height, `keyartFocusX` the horizontal point to keep on narrow\n",
        "-- screens) and the stencilled metal logo (tools/ui/title_logo.py).\n\n",
        "return {\n",
        f'\ticons = "{ids["weapon_icons"]}",\n',
        "\ticonCells = {\n",
    ]
    for name in sorted(meta["icons"]["cells"]):
        c = meta["icons"]["cells"][name]
        (x, y), (w, h) = c["offset"], c["size"]
        lines.append(f"\t\t{name} = {{ offset = Vector2.new({x}, {y}), size = Vector2.new({w}, {h}) }},\n")
    lines.append("\t},\n")
    key = meta.get("keyart")
    if key and "title_keyart" in ids:
        lines += [
            f'\tkeyart = "{ids["title_keyart"]}",\n',
            f"\tkeyartAspect = {key['aspect']},\n",
            f"\tkeyartFocusX = {key['focus_x']},\n",
        ]
    else:
        lines += ["\tkeyart = nil :: string?,\n", "\tkeyartAspect = 16 / 9,\n", "\tkeyartFocusX = 0.62,\n"]
    lines += [
        f'\tlogo = "{ids["title_logo"]}",\n',
        f"\tlogoSize = Vector2.new({logo_w}, {logo_h}),\n",
        "}\n",
    ]
    luau.write_text("".join(lines))
    print("wrote", luau.relative_to(ROOT))


def main(argv: list[str]) -> int:
    set_name = "look"
    if "--set" in argv:
        i = argv.index("--set")
        set_name = argv[i + 1]
        argv = argv[:i] + argv[i + 2:]
    if set_name not in SETS:
        print(f"unknown set {set_name}; one of {', '.join(SETS)}")
        return 2
    if argv and argv[0] == "upload":
        upload(set_name, argv[1:])
        return 0
    if argv and argv[0] == "luau":
        {"kit": write_kit_luau, "motion": write_motion_luau, "art": write_art_luau}.get(set_name, write_look_luau)()
        return 0
    print(__doc__)
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
