#!/usr/bin/env python3
"""Uploads the environment textures and writes the Luau data modules.

    set -a; . ./.env.local; set +a            # Open Cloud credentials (never printed)
    python3 tools/env/publish_env.py upload terrain [Name ...]
    python3 tools/env/publish_env.py upload sky [Preset ...]
    python3 tools/env/publish_env.py luau [--out DIR]  # src/shared/TerrainMaterials.luau + SkyAssets.luau

Images go up as private `Image` assets through tools/assets/opencloud.py;
ids are cached per file hash in assets/textures/<kind>/roblox_ids.json, so
unchanged files are skipped. The Luau modules are generated from the
manifests, the id caches and tools/env/sky_presets.json (Roblox settings).
"""
import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "tools" / "assets"))
import opencloud  # noqa: E402

TERRAIN = ROOT / "assets" / "textures" / "terrain"
SKY = ROOT / "assets" / "textures" / "sky"
SKY_PRESETS = ROOT / "tools" / "env" / "sky_presets.json"
FACES = ["Bk", "Dn", "Ft", "Lf", "Rt", "Up"]


def sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()[:16]


def load_ids(path: Path) -> dict:
    return json.loads(path.read_text()) if path.exists() else {"hashes": {}, "ids": {}}


def save_ids(path: Path, ids: dict) -> None:
    path.write_text(json.dumps(ids, indent=1, sort_keys=True) + "\n")


def upload_file(ids: dict, key: str, f: Path, display: str) -> bool:
    h = sha(f)
    if ids["hashes"].get(key) == h and ids["ids"].get(key):
        return False
    res = opencloud.upload(str(f), "Image", display, "Red Mesa Holdout environment texture")
    ids["ids"][key] = f"rbxassetid://{res['assetId']}"
    ids["hashes"][key] = h
    print(f"uploaded {key}: {res['assetId']}")
    return True


def upload_terrain(names: list[str]) -> None:
    ids_path = TERRAIN / "roblox_ids.json"
    ids = load_ids(ids_path)
    names = names or sorted(p.parent.name for p in TERRAIN.glob("*/manifest.json"))
    for name in names:
        man = json.loads((TERRAIN / name / "manifest.json").read_text())
        for ch, fname in man["files"].items():
            if upload_file(ids, f"{name}/{ch}", TERRAIN / name / fname, f"RMH_Terrain_{name}_{ch}"):
                save_ids(ids_path, ids)
    save_ids(ids_path, ids)
    print("terrain ids:", ids_path.relative_to(ROOT))


def upload_sky(presets: list[str]) -> None:
    ids_path = SKY / "roblox_ids.json"
    ids = load_ids(ids_path)
    presets = presets or sorted(p.name for p in SKY.iterdir() if p.is_dir())
    for preset in presets:
        for face in FACES:
            f = SKY / preset / f"{preset}_{face}.png"
            if upload_file(ids, f"{preset}/{face}", f, f"RMH_Sky_{preset}_{face}"):
                save_ids(ids_path, ids)
    save_ids(ids_path, ids)
    print("sky ids:", ids_path.relative_to(ROOT))


# ------------------------------------------------------------------ Luau
def lua_value(v) -> str:
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return repr(round(v, 4)) if isinstance(v, float) else str(v)
    if isinstance(v, str):
        if v.startswith("#") and len(v) == 7:
            return f"Color3.fromRGB({int(v[1:3], 16)}, {int(v[3:5], 16)}, {int(v[5:7], 16)})"
        return json.dumps(v)
    raise TypeError(v)


TERRAIN_HEADER = '''--!strict
-- GENERATED by tools/env/publish_env.py luau — do not edit by hand.
-- Terrain MaterialVariants (ENV-1): custom PBR sets for every terrain
-- material TerrainBuilder paints. Sources and recipes: tools/env/,
-- textures: assets/textures/terrain/<Name>/. Applied by TerrainBuilder
-- through MaterialService (variant + base-material override).
--
-- `surface` names what each terrain material looks like, for impact
-- effects that pick sand/rock/dirt by raycast material (e.g. Mud is used
-- for the coarse-sand patches on the basin floor and should kick up sand).

export type Variant = {
	name: string,
	baseMaterial: Enum.Material,
	studsPerTile: number,
	pattern: Enum.MaterialPattern,
	colorMap: string,
	normalMap: string,
	roughnessMap: string,
	surface: string,
}

local TerrainMaterials = {}

local VARIANTS: { Variant } = {
'''

SURFACE = {"Sand": "Sand", "SandCoarse": "Sand", "Road": "Ground", "Wash": "Sand",
           "Rock": "Rock", "Sandstone": "Rock", "Limestone": "Rock", "Slate": "Rock"}


def write_terrain_luau(out_dir: Path) -> Path:
    ids = load_ids(TERRAIN / "roblox_ids.json")["ids"]
    lines = [TERRAIN_HEADER]
    for man_path in sorted(TERRAIN.glob("*/manifest.json")):
        m = json.loads(man_path.read_text())
        name = m["name"]
        if not all(f"{name}/{ch}" in ids for ch in ("color", "normal", "roughness")):
            print(f"skip {name}: not uploaded")
            continue
        lines.append("\t{\n")
        lines.append(f'\t\tname = "{m["variant"]}",\n')
        lines.append(f"\t\tbaseMaterial = Enum.Material.{m['base_material']},\n")
        lines.append(f"\t\tstudsPerTile = {m['studs_per_tile']},\n")
        lines.append(f"\t\tpattern = Enum.MaterialPattern.{m['pattern']},\n")
        lines.append(f'\t\tcolorMap = "{ids[f"{name}/color"]}",\n')
        lines.append(f'\t\tnormalMap = "{ids[f"{name}/normal"]}",\n')
        lines.append(f'\t\troughnessMap = "{ids[f"{name}/roughness"]}",\n')
        lines.append(f'\t\tsurface = "{SURFACE.get(name, "Rock")}",\n')
        lines.append("\t},\n")
    lines.append("}\n\nTerrainMaterials.VARIANTS = VARIANTS\n\n")
    lines.append('''-- What a terrain material looks like ("Sand", "Ground", "Rock"), or nil.
function TerrainMaterials.surfaceOf(material: Enum.Material): string?
	for _, v in TerrainMaterials.VARIANTS do
		if v.baseMaterial == material then
			return v.surface
		end
	end
	return nil
end

return TerrainMaterials
''')
    out = out_dir / "TerrainMaterials.luau"
    out.write_text("".join(lines))
    return out


SKY_HEADER = '''--!strict
-- GENERATED by tools/env/publish_env.py luau — do not edit by hand.
-- Skyboxes per time-of-day preset (ENV-1), rendered in Blender from a
-- procedural sky (tools/env/sky.py + sky.osl; images in
-- assets/textures/sky/<Preset>/). Consumed by Look's TimeOfDay/LightingRig
-- through pcall(require, ...); a missing preset means "keep the current sky".
--
-- Each preset:
--   faces: SkyboxBk/Dn/Ft/Lf/Rt/Up image ids
--   sky: other Sky properties (sun/moon/stars)
--   clouds: Workspace.Terrain.Clouds properties (Enabled=false removes cover)
--   authoredSun: the Roblox sun direction the sky's glow was painted for
--                (Lighting:GetSunDirection() at `clockTime`, latitude 30)

export type Preset = {
	faces: { [string]: string },
	sky: { [string]: any },
	clouds: { [string]: any },
	clockTime: number,
	authoredSun: Vector3,
}

local SkyAssets = {}

local PRESETS: { [string]: Preset } = {
'''


def write_sky_luau(out_dir: Path) -> Path:
    ids = load_ids(SKY / "roblox_ids.json")["ids"]
    presets = json.loads(SKY_PRESETS.read_text())
    lines = [SKY_HEADER]
    for name, p in presets.items():
        if p.get("test"):
            continue
        source = p.get("faces_from", name)
        if not all(f"{source}/{f}" in ids for f in FACES):
            print(f"skip {name}: faces not uploaded")
            continue
        rb = p.get("roblox", {})
        lines.append(f"\t{name} = {{\n\t\tfaces = {{\n")
        for f in FACES:
            lines.append(f'\t\t\tSkybox{f} = "{ids[f"{source}/{f}"]}",\n')
        lines.append("\t\t},\n\t\tsky = {\n")
        for k, v in rb.get("sky", {}).items():
            lines.append(f"\t\t\t{k} = {lua_value(v)},\n")
        lines.append("\t\t},\n\t\tclouds = {\n")
        for k, v in rb.get("clouds", {}).items():
            lines.append(f"\t\t\t{k} = {lua_value(v)},\n")
        sun = p["sun"]
        lines.append("\t\t},\n")
        lines.append(f"\t\tclockTime = {p.get('clock', 12)},\n")
        lines.append(f"\t\tauthoredSun = Vector3.new({sun[0]}, {sun[1]}, {sun[2]}),\n")
        lines.append("\t},\n")
    lines.append("}\n\nSkyAssets.PRESETS = PRESETS\n\nreturn SkyAssets\n")
    out = out_dir / "SkyAssets.luau"
    out.write_text("".join(lines))
    return out


def main(argv: list[str]) -> int:
    if len(argv) >= 2 and argv[0] == "upload" and argv[1] == "terrain":
        upload_terrain(argv[2:])
        return 0
    if len(argv) >= 2 and argv[0] == "upload" and argv[1] == "sky":
        upload_sky(argv[2:])
        return 0
    if argv and argv[0] == "luau":
        out_dir = Path(argv[argv.index("--out") + 1]) if "--out" in argv else ROOT / "src" / "shared"
        print("wrote", write_terrain_luau(out_dir))
        print("wrote", write_sky_luau(out_dir))
        return 0
    print(__doc__)
    return 2


if __name__ == "__main__":
    try:
        sys.exit(main(sys.argv[1:]))
    except opencloud.OpenCloudError as e:
        print(f"error: {e}", file=sys.stderr)
        sys.exit(1)
