#!/usr/bin/env python3
"""Live-terrain heightfield along the road and wash corridors (ENV-3).

The ground strips must lie on the terrain Roblox actually builds (voxelised
on a 4-stud grid, smooth-meshed), not on TerrainBuilder's analytic shapes.
A Studio snippet raycasts the live terrain on a 2-stud grid inside each
corridor (playtest, Server datamodel) and records, per sample:
  - the terrain height and material (paint bands: Ground road, Salt wash),
  - the height of the mesa landscape mesh there, if any (where the talus
    covers the strip end).

  python3 tools/env/ground/sink.py /tmp/probe_in &      # local sink (Studio -> files)
  python3 tools/env/ground/probe.py snippet            # -> .probe_run.luau (+ row lists)
  (run .probe_run.luau in the Server datamodel of a playtest)
  python3 tools/env/ground/probe.py save <batch> /tmp/probe_in/probe_<batch>.txt   # each batch
  python3 tools/env/ground/probe.py stats              # coverage, paint-band widths

`load(corridor)` returns the grid as numpy arrays for strips.py.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import paths  # noqa: E402

ROOT = HERE.parents[2]
OUT = ROOT / "assets" / "source" / "ground"
STEP = 2.0
MAX_SAMPLES = 17000  # per batch (5 chars per sample)
B64 = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"
MATERIALS = ["Sand", "Mud", "Ground", "Salt", "Rock", "Sandstone", "Limestone", "Slate"]
Y0, YQ = 40.0, 25.0  # y = code / YQ - Y0  (0.04-stud steps, -40..123)

RUNNER = """-- Generated by tools/env/ground/probe.py: live terrain + mesa mesh heights for
-- every corridor batch. Rows come from the local sink (GET), results go back to
-- it (POST): run `python3 tools/env/ground/sink.py <out_dir>` first.
local Http = game:GetService("HttpService")
Http.HttpEnabled = true
local B = "{b64}"
local MATS = {{ {mats} }}
local function enc(v)
	v = math.clamp(math.floor(v + 0.5), 0, 4095)
	local hi, lo = v // 64, v % 64
	return string.sub(B, hi + 1, hi + 1) .. string.sub(B, lo + 1, lo + 1)
end
local tp = RaycastParams.new()
tp.FilterType = Enum.RaycastFilterType.Include
tp.FilterDescendantsInstances = {{ workspace.Terrain }}
local mesa = {{}}
for _, d in workspace.Battlefield.Landscape:GetDescendants() do
	if d:IsA("BasePart") and string.sub(d.Name, 1, 4) == "Mesa" then table.insert(mesa, d) end
end
local lp = RaycastParams.new()
lp.FilterType = Enum.RaycastFilterType.Include
lp.FilterDescendantsInstances = mesa
local report = {{}}
for _, batch in {{ {batches} }} do
	local rows = Http:JSONDecode(Http:GetAsync("http://localhost:34999/.probe_" .. batch .. ".rows.json"))
	for _, p in mesa do p.CanQuery = true end
	local out = {{}}
	local ok, err = pcall(function()
		for _, r in rows do
			local z, x0, n = r[1], r[2], r[3]
			local parts = table.create(n)
			for i = 0, n - 1 do
				local x = x0 + i * {step}
				local hit = workspace:Raycast(Vector3.new(x, 300, z), Vector3.new(0, -360, 0), tp)
				local s = if hit then enc((hit.Position.Y + {y0}) * {yq}) .. (MATS[hit.Material.Name] or "z") else "~~z"
				local lh = if x * x + z * z < 200 * 200 then workspace:Raycast(Vector3.new(x, 300, z), Vector3.new(0, -360, 0), lp) else nil
				parts[i + 1] = s .. (if lh then enc((lh.Position.Y + {y0}) * {yq}) else "!!")
			end
			out[#out + 1] = table.concat(parts)
		end
	end)
	for _, p in mesa do p.CanQuery = false end
	if not ok then error(err) end
	local result = #mesa .. "|" .. table.concat(out, ";")
	Http:PostAsync("http://localhost:34999/probe_" .. batch .. ".txt", result, Enum.HttpContentType.TextPlain)
	table.insert(report, batch .. " " .. #result)
end
return table.concat(report, ", ")
"""


def corridor_rows(name: str):
    """(z, x0, n) rows of grid samples within the corridor's half-width."""
    poly = paths.extended(name)
    half = paths.CORRIDORS[name][2]
    lo = np.floor((poly.min(axis=0) - half) / STEP) * STEP
    hi = np.ceil((poly.max(axis=0) + half) / STEP) * STEP
    xs = np.arange(lo[0], hi[0] + STEP / 2, STEP)
    rows = []
    for z in np.arange(lo[1], hi[1] + STEP / 2, STEP):
        pts = np.stack([xs, np.full_like(xs, z)], axis=1)
        inside = paths.dist_to_polyline(pts, poly) <= half
        idx = np.flatnonzero(inside)
        if len(idx) == 0:
            continue
        # contiguous runs
        breaks = np.flatnonzero(np.diff(idx) > 1)
        starts = np.concatenate([[idx[0]], idx[breaks + 1]])
        ends = np.concatenate([idx[breaks], [idx[-1]]])
        for a, b in zip(starts, ends):
            rows.append((float(z), float(xs[a]), int(b - a + 1)))
    return rows


def batches():
    out = []
    for name in paths.CORRIDORS:
        rows = corridor_rows(name)
        cur, count, k = [], 0, 0
        for r in rows:
            if count + r[2] > MAX_SAMPLES and cur:
                out.append((f"{name}{k}", cur))
                cur, count, k = [], 0, k + 1
            cur.append(r)
            count += r[2]
        if cur:
            out.append((f"{name}{k}", cur))
    return out


def snippet() -> None:
    mats = ", ".join(f'{m} = "{B64[i]}"' for i, m in enumerate(MATERIALS))
    names = []
    for batch, rows in batches():
        (HERE / f".probe_{batch}.rows.json").write_text(json.dumps(rows))
        names.append(f'"{batch}"')
        print(f"rows for {batch}: {sum(r[2] for r in rows)} samples")
    code = RUNNER.format(b64=B64, mats=mats, batches=", ".join(names), step=STEP, y0=Y0, yq=YQ)
    path = HERE / ".probe_run.luau"
    path.write_text(code)
    print(f"wrote {path.relative_to(ROOT)}: run it in the Server datamodel of a playtest (~40 s after Play,")
    print("once the mesa's precise collision is built) with `sink.py <out_dir>` running; then `probe.py save`.")


def save(batch: str, src: str) -> None:
    text = Path(src).read_text().strip()
    if text.startswith('"'):
        text = json.loads(text)
    rows = json.loads((HERE / f".probe_{batch}.rows.json").read_text())
    mesa, _, body = text.partition("|")
    lines = body.split(";")
    assert len(lines) == len(rows), f"expected {len(rows)} rows, got {len(lines)}"
    for (z, x, n), line in zip(rows, lines):
        assert len(line) == 5 * n, f"row z={z}: expected {5 * n} chars, got {len(line)}"
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / f"probe_{batch}.json").write_text(json.dumps({"mesa_parts": int(mesa), "rows": rows, "data": lines}))
    print(f"saved {batch}: {len(rows)} rows, {sum(r[2] for r in rows)} samples, {mesa} mesa parts")


def _dec(c2: str) -> float:
    if c2 in ("!!", "~~"):
        return np.nan
    return (B64.index(c2[0]) * 64 + B64.index(c2[1])) / YQ - Y0


def load(name: str):
    """Grid for one corridor: x (W,), z (H,), terrain y (H, W), material codes
    (H, W, -1 = none/outside), mesa mesh y (H, W, nan = none)."""
    samples = []
    for f in sorted(OUT.glob(f"probe_{name}[0-9]*.json")):
        d = json.loads(f.read_text())
        for (z, x0, n), line in zip(d["rows"], d["data"]):
            for i in range(n):
                s = line[5 * i:5 * i + 5]
                mat = B64.index(s[2]) if s[2] in B64[:len(MATERIALS)] else -1
                samples.append((x0 + i * STEP, z, _dec(s[0:2]), mat, _dec(s[3:5])))
    if not samples:
        raise SystemExit(f"no probe data for {name}: run the snippets (probe.py snippet) and save them")
    a = np.array(samples)
    xs = np.unique(a[:, 0])
    zs = np.unique(a[:, 1])
    ix = np.searchsorted(xs, a[:, 0])
    iz = np.searchsorted(zs, a[:, 1])
    y = np.full((len(zs), len(xs)), np.nan)
    mat = np.full((len(zs), len(xs)), -1, dtype=np.int32)
    land = np.full((len(zs), len(xs)), np.nan)
    y[iz, ix] = a[:, 2]
    mat[iz, ix] = a[:, 3].astype(np.int32)
    land[iz, ix] = a[:, 4]
    return xs, zs, y, mat, land


def stats() -> None:
    for name in paths.CORRIDORS:
        xs, zs, y, mat, land = load(name)
        poly = paths.extended(name)
        X, Z = np.meshgrid(xs, zs)
        pts = np.stack([X.ravel(), Z.ravel()], axis=1)
        d = paths.dist_to_polyline(pts, np.array(paths.lanes()[name])).reshape(X.shape)
        paint = MATERIALS.index("Ground" if name == "Road" else "Salt")
        painted = mat == paint
        print(f"{name}: {np.isfinite(y).sum()} samples, y {np.nanmin(y):.2f}..{np.nanmax(y):.2f}; "
              f"{MATERIALS[paint]} out to {d[painted].max():.1f} studs from the lane; "
              f"mesa mesh over {np.isfinite(land).sum()} samples")
        for m in np.unique(mat[mat >= 0]):
            print(f"   {MATERIALS[m]:10s} {np.sum(mat == m):6d}")


def main(argv):
    if not argv:
        print(__doc__)
        return 2
    if argv[0] == "snippet":
        snippet()
    elif argv[0] == "save":
        save(argv[1], argv[2])
    elif argv[0] == "stats":
        stats()
    else:
        print(__doc__)
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
