#!/usr/bin/env python3
"""Upload the ground strips and dressing and write their .rbxmx (ENV-3, ENV-4).

Uses the shared pipeline (tools/assets/publish.py, rbxmx.py, read-only) for
uploads and harvests; writes its own rbxmx because these parts need
properties the generic writer doesn't set: per-part AlphaMode (alpha
cards/edges vs opaque pieces sharing one colour map), DoubleSided cards,
rotated chunk frames, RenderFidelity, pivot offsets and terrain materials.

  set -a; . ./.env.local; set +a
  .venv-env/bin/python tools/env/ground/publish.py upload            # GLBs + maps (skips unchanged)
  .venv-env/bin/python tools/env/ground/publish.py harvest           # -> tools/env/ground/.probe_harvest.luau
      run it in Studio (Edit) with `sink.py <out_dir>` running; it posts harvest_ground.json there
  .venv-env/bin/python tools/env/ground/publish.py meshes <json>     # ids -> assets/roblox/Ground*.rbxmx
  .venv-env/bin/python tools/env/ground/publish.py rbxmx             # regenerate from cached ids
"""
from __future__ import annotations

import importlib.util
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT / "tools" / "assets"))

_spec = importlib.util.spec_from_file_location("assets_publish", ROOT / "tools" / "assets" / "publish.py")
pipeline = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(pipeline)
R = pipeline.rbxmx

# ENV-4 (tools/env/dressing/meshes.py): GroundPatches (flat alpha patches,
# lane trample, concertina wire) and ConflictDressing (props on one atlas).
NAMES = ["GroundStrips", "GroundDressing", "GroundPatches", "ConflictDressing"]
MATERIAL = {"Ground": 1360, "Salt": 1392, "Sand": 1296, "Grass": 1280, "Wood": 512, "Rock": 896,
            "Concrete": 816, "Brick": 848, "Fabric": 1312, "Metal": 1088, "CorrodedMetal": 1040,
            "Plastic": 256, "Rubber": 256, "WoodPlanks": 512}
ALPHA = {"Overlay": 0, "Transparency": 1, "Opaque": 3}
# strips Precise (no LOD pop); everything else Automatic (engine LODs)
FIDELITY = {"GroundStrips": 1, "GroundDressing": 0, "GroundPatches": 0, "ConflictDressing": 0}
HARVEST = """-- Generated by tools/env/ground/publish.py harvest: MeshIds of the uploaded
-- models, posted to the local sink (tools/env/ground/sink.py) as harvest_ground.json.
local result, counts = {{}}, {{}}
for name, id in {{ {entries} }} do
	local model = game:GetService("InsertService"):LoadAsset(id)
	local out, n = {{}}, 0
	for _, d in model:GetDescendants() do
		if d:IsA("MeshPart") then
			out[d.Name] = {{ id = d.MeshId, size = {{ d.Size.X, d.Size.Y, d.Size.Z }} }}
			n += 1
		end
	end
	model:Destroy()
	result[name] = out
	counts[#counts + 1] = name .. " " .. n
end
local Http = game:GetService("HttpService")
local was = Http.HttpEnabled
Http.HttpEnabled = true
Http:PostAsync("http://localhost:34999/harvest_ground.json", Http:JSONEncode(result), Enum.HttpContentType.ApplicationJson)
Http.HttpEnabled = was
return table.concat(counts, ", ")
"""
TERRAIN_IDS = ROOT / "assets" / "textures" / "terrain" / "roblox_ids.json"


def terrain_maps(name: str) -> dict:
    ids = json.loads(TERRAIN_IDS.read_text())["ids"]
    return {"color": ids[f"{name}/color"], "normal": ids[f"{name}/normal"]}


def write_rbxmx(name: str) -> None:
    _, manifest, ids, _ = pipeline.load(name)
    tex = dict(ids.get("textures", {}))
    for group, terrain in manifest.get("terrain_textures", {}).items():
        tex[group] = terrain_maps(terrain)
    meshes = ids.get("meshes", {})
    ref = R.Ref()
    root = R.Node("Model", name, ref())
    for p in manifest["parts"]:
        mesh = meshes.get(p["name"])
        if mesh is None:
            raise SystemExit(f"{name}: no mesh id for {p['name']} (harvest first)")
        node = R.Node("MeshPart", p["name"], ref())
        rot = tuple(tuple(r) for r in p["rotation"]) if p.get("rotation") else R.IDENTITY
        node.props += [
            R.prop("Content", "MeshId", mesh["id"] if isinstance(mesh, dict) else mesh),
            R.vec3("InitialSize", p["size"]),
            R.vec3("size", p["size"]),
            R.cframe_xml("CoordinateFrame", "CFrame", p["center"], rot),
            R.prop("bool", "Anchored", True),
            R.prop("bool", "CanCollide", False),
            R.prop("bool", "CanQuery", False),
            R.prop("bool", "CanTouch", False),
            R.prop("bool", "CastShadow", bool(p.get("shadow", False))),
            R.prop("bool", "DoubleSided", bool(p.get("double_sided", False))),
            R.prop("token", "CollisionFidelity", R.FIDELITY["Box"]),
            R.prop("token", "RenderFidelity", FIDELITY[name]),
            R.prop("float", "Transparency", 0),
            R.prop("token", "Material", MATERIAL[p["material"]]),
            R.color3(p.get("color", (1, 1, 1))),
        ]
        if p.get("pivot_offset") is not None:
            node.props.append(R.cframe_xml("CoordinateFrame", "PivotOffset", p["pivot_offset"]))
        maps = tex.get(p["tex"], {})
        sa = R.Node("SurfaceAppearance", "SurfaceAppearance", ref())
        for key, prop_name in (("color", "ColorMap"), ("normal", "NormalMap"), ("rough", "RoughnessMap"), ("metal", "MetalnessMap")):
            if maps.get(key):
                sa.props.append(R.prop("Content", prop_name, maps[key]))
            else:
                sa.props.append(f'<Content name="{prop_name}"><null></null></Content>')
        sa.props.append(R.prop("token", "AlphaMode", ALPHA[p.get("alpha", "Overlay")]))
        node.children.append(sa)
        root.children.append(node)
    root.props.append(R.cframe_xml("OptionalCoordinateFrame", "WorldPivotData", [0.0, 0.0, 0.0]))
    xml = f'<roblox xmlns:xmime="http://www.w3.org/2005/05/xmlmime" version="4">\n{root.xml()}\n</roblox>\n'
    target = ROOT / "assets" / "roblox" / f"{name}.rbxmx"
    target.write_text(xml)
    print(f"wrote {target.relative_to(ROOT)} ({len(manifest['parts'])} parts)")


def store_meshes(name: str, data: dict) -> None:
    _, manifest, ids, ids_path = pipeline.load(name)
    problems = []
    for p in manifest["parts"]:
        m = data.get(p["name"])
        if not m:
            problems.append(f"missing mesh for {p['name']}")
            continue
        got, want = m["size"], p["size"]
        if any(abs(g - w) > max(0.05, 0.02 * w) for g, w in zip(got, want)):
            problems.append(f"{p['name']}: imported size {got} != manifest {want}")
    if problems:
        print("WARNING:\n  " + "\n  ".join(problems))
    ids["meshes"] = {k: v["id"] for k, v in data.items()}
    pipeline.save_ids(ids_path, ids)


def main(argv):
    if not argv:
        print(__doc__)
        return 2
    cmd, rest = argv[0], argv[1:]
    names = [n for n in rest if n in NAMES] or NAMES
    if cmd == "upload":
        for n in names:
            pipeline.upload(n)
    elif cmd == "harvest":
        entries = ", ".join(f"{n} = {pipeline.load(n)[2]['model']}" for n in names)
        path = Path(__file__).resolve().parent / ".probe_harvest.luau"
        path.write_text(HARVEST.format(entries=entries))
        print(f"wrote {path.relative_to(ROOT)}")
    elif cmd == "meshes":
        text = Path(rest[0]).read_text()
        data = json.loads(text)
        if isinstance(data, str):
            data = json.loads(data)
        for name, meshes in data.items():
            store_meshes(name, meshes)
            write_rbxmx(name)
    elif cmd == "rbxmx":
        for n in names:
            write_rbxmx(n)
    else:
        print(__doc__)
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
