"""Writes src/client/SfxSheet.luau from assets/audio/sfx_sheet.json.
Usage: python3 tools/audio/make_luau.py <audio asset id>"""
import json, pathlib, sys

root = pathlib.Path(__file__).resolve().parents[2]
manifest = json.loads((root / "assets/audio/sfx_sheet.json").read_text())
asset_id = sys.argv[1]
lines = [
    "--!strict",
    "-- GENERATED by tools/audio/make_luau.py — do not edit by hand.",
    "-- One uploaded sound sheet of original synthesized effects; each entry is",
    "-- a playback region (seconds) inside it.",
    "",
    "return {",
    f'\tSoundId = "rbxassetid://{asset_id}",',
    "\tRegions = {",
]
for name, r in manifest.items():
    loop = "true" if r["loop"] else "false"
    lines.append(f'\t\t{name} = {{ start = {r["start"]}, stop = {r["stop"]}, loop = {loop} }},')
lines += ["\t},", "}", ""]
(root / "src/client/SfxSheet.luau").write_text("\n".join(lines))
print("wrote", len(manifest), "regions")
